### ISSUE TITLE
Menu button has to be clicked twice.

### ISSUE THREAD

**Issue by ScottRFrost** [Quicksaver/The-Fox--Only-Better#105]
Firefox Dev edition / Aurora 40.0a2 (2015-06-09) 
64 bit windows build
e10s enabled

When I move the mouse to the top, everything renders correctly.  I can click on download arrow, favorites, uBlock, etc with a single click.  However, the (hamburger) menu has to be clicked twice.  The first click just seems to highlight it.  This behavior occurs even if "Also hide the navigation bar" is UNchecked.

**Comment by Quicksaver** [comment]
Does that happen if you disable Slim Chrome as well and not just uncheck "Also hide the navigation bar"?

Could you also please try the latest beta version 1.1.14b2 (https://addons.mozilla.org/firefox/addon/the-fox-only-better/versions/) and see if it also happens with it? If it does, please try disabling all your other add-ons and themes and see if that makes a difference as well.

**Comment by ScottRFrost** [comment]
The latest beta appears to have resolved it.

**Comment by Quicksaver** [comment]
I'm glad to hear that, let me know if it happens again.
