### ISSUE TITLE
Issue with Simplify Awesome Bar addon

### ISSUE THREAD

**Issue by tunguyen6** [Quicksaver/The-Fox--Only-Better#108]
Hi. I have an issue using TFOB with Simplify Awesome Bar (https://addons.mozilla.org/firefox/addon/simplify-awesome-bar/). Occasionally the navigation bar re-hides after a few letters are typed.
I'm using Firefox 39.0 on Windows 8.1 64 bit. I tried disabling all other addons except for the two but the problem persisted, so it did after I created a new Firefox profile and installed them.

**Comment by Quicksaver** [comment]
So I just tried it again and it always seems to work fine for me. Can you give me some exact steps from which you can faithfully reproduce this, from when you start firefox to the point the location bar hides when it shouldn't? Or does it happen apparently randomly?

**Comment by tunguyen6** [comment]
This is a gif I made in a new Firefox profile
![file](https://cloud.githubusercontent.com/assets/13366492/8745938/a780334c-2cae-11e5-8584-0877a28250c3.gif)
It does not happen all the time.
Howerver, I accidentally found out that by disabling location bar suggestion in Firefox settings the problem would disappear. I might need to test more.

**Comment by Quicksaver** [comment]
In that specific case how did you first get the cursor into the location bar, by pressing "t" while nothing is focused?

**Comment by tunguyen6** [comment]
That is the function of Simplify Awesome Bar, "type when the cursor is not in any input-able field and this extension will bring us straight into the Awesome Bar". So with that addon enabled, I just typed.

**Comment by Quicksaver** [comment]
I have only been able to reproduce this once, and I still have no idea how exactly I did that or what is happening that can lead to this.

But I had an idea of how to avoid it. Could you give beta version 1.2.1b1 a try (https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.2.1b1) and see if it still happens for you? Since this seems to happen much more frequently for you, I really would appreciate it if you could test it out.

**Comment by tunguyen6** [comment]
It's been working! I think the problem's gone now. So much thanks for the fix. I will contact you if it happens again.

**Comment by Quicksaver** [comment]
I'm glad to hear it. If you have any other problems just let me know.
