### ISSUE TITLE
Windows 10/Firefox 39 Tabs flashing black when chrome/minibar is displayed

### ISSUE THREAD

**Issue by bwiernik** [Quicksaver/The-Fox--Only-Better#109]
I just updated to Windows 10. Now, when the chrome is displayed when changing tabs or hovering over links, a subset of the tab bar turns black in color. No functionality is lost, but the frequent color changes are rather distracting.

**Comment by Quicksaver** [comment]
Can you post a screenshot of when the tab bar turns black please? And does the same happen if you disable all your add-ons except for TFOB?

By the way, I don't currently have Windows 10 installed, and it may still take a month or two until I upgrade to it. So depending on the cause, it may not be possible for me to fix this at the moment.

**Comment by bwiernik** [comment]
Here is a screenshot. The amount of the tab bar that turns black varies seemingly randomly.

![screen shot 2015-08-04 at 13 18 22](https://cloud.githubusercontent.com/assets/4773225/9068836/679b3cf8-3aab-11e5-8294-ee30bb07a1df.png)

**Comment by Quicksaver** [comment]
That is indeed very weird. Does it happen when you disable all other add-ons except for TFOB? And also, in the add-on's preferences, if you change the style from Australis to anything else, does it also happen?

**Comment by bwiernik** [comment]
It happens when I change to any of the themes. Once I disabled everything but TFOB, it stopped happening, so it seems to be a compatibility issue with another addon. The offending one seems to be https://addons.mozilla.org/en-US/firefox/addon/noiascrollbars/ 

So, I guess this isn't really a bug with TFOB. Sorry for the bother.

**Comment by Quicksaver** [comment]
A compatibility issue with another add-on or theme is still an issue with TFOB. So you have nothing to apologize. ;)

I'll take a look at NoiaScrollbars some time later today and I'll get back to you.

**Comment by Aris-t2** [comment]
I have tested TFOB & NewScrollbars with a Fx new profile on Windows 10 Pro and could not reproduce such glitches. Are you using add-ons default settings or something special? Please provide your configuration.

NewScrollbars does not contain any code that affects tabs, tabs toolbar titlebar or anything else not scrollbar related.

@bwiernik
Could you disable "Hardware Acceleration" inside Firefox settings and test TFOB and NewScrollbars on a new Fx profile?

**Comment by Quicksaver** [comment]
I also can't reproduce it, but as I said I'm not on Windows 10, so my results are irrelevant for now.

@Aris-t2 thanks for checking it out. I did take a quick look at NewScrollbars' code, to see if anything popped out. I noticed a couple of cases where it sets the background color for ```#appcontent``` and ```#content```, Maybe that's what's appearing behind the tabs there somehow? Enabling neither the **Transparent v2** or the **On top of webcontent/Transparent scrollbar background** (if I read that correctly, those are the settings that set those background properties?) is causing the issue for me, but again, maybe it's a Win10-only issue.

@bwiernik are you by chance using either of those settings in your NewScrollbars options? As Aris asked, a screenshot of your NewScrollbars settings sure would be nice. I'd also like to know if any of Aris suggestions works as well.

**Comment by Aris-t2** [comment]
#appcontent / #content nodes do not overlap with top or bottom toolbars, so I don't think they can affect tabs toolbar. My guess: an incompatible video driver is causing this for bwiernik.

@Quicksaver 
No need to "upgrade" or switch to Windows 10 yet. Just install use Windows 10 Enterprise (90-day trial) in VirtualBox.

**Comment by Quicksaver** [comment]
True, those were the only properties not directly related to the scrollbars at all, which is the only reason I suggested them. Considering the kinds of weirdness I run into sometimes, that would have actually been a "reasonable" explanation. :)

If those are not causing it, then as you said, nothing in NewScrollbars seems to come even remotely close to the tabs toolbar.

**Comment by Quicksaver** [comment]
@bwiernik do you still have the issue in Firefox 41 with the beta version of the add-on at https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.3.2b3 ?

**Comment by bwiernik** [comment]
Not having the issue anymore.

Brenton Wiernik

Email: wiernik@umn.edu
Phone: +1 (715) 204-4252
wiernik.workpsy.ch




On Sat, Oct 10, 2015 at 12:43 AM -0700, "Luís Miguel" <notifications@github.com> wrote:












@bwiernik do you still have the issue in Firefox 41 with the beta version of the add-on at https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.3.2b3 ?

**Comment by Quicksaver** [comment]
Great! Let me know if it happens again.
