### ISSUE TITLE
navigation toolbar: remove background color

### ISSUE THREAD

**Issue by mikeparadinas** [Quicksaver/The-Fox--Only-Better#110]
Classic Theme Restorer had a great little option called "navigation toolbar: remove background color"
This would remove a white foggy thing that would ruin my persona's

I discovered TheFox-OnlyBetter and I love it, More web pixels +1
However this option I mentioned before doesn't work anymore, The white fog is back and makes using TheFox hard to look at for me personally.

Is there a fix, a Stylish code maybe? or just a fix in the fox itself?

![tfob1](https://cloud.githubusercontent.com/assets/13681989/9118201/22744096-3c6f-11e5-89c2-3bb039c39c8f.png)

Thanks Quicksaver your addons are amazing!

**Comment by Quicksaver** [comment]
You're right of course, thanks for letting me know! This will be fixed in the next release.

**Comment by Quicksaver** [comment]
@Aris-t2, just letting you know, in case any user comes to you about this issue in the meantime, that you can tell them this will be fixed in the next TFOB release.
