### ISSUE TITLE
URL bar looks bad in ff 40.0.2

### ISSUE THREAD

**Issue by FlameRaptor** [Quicksaver/The-Fox--Only-Better#112]
When I use the compact style In ff 40.02, the URL bar is much thicker than the search bar. No problem with other three styles. This occurs while using 1.2.1 and 1.2.2b1.

**Comment by Quicksaver** [comment]
Should already be fixed in final 1.2.2 (https://addons.mozilla.org/firefox/addon/the-fox-only-better/versions/)

**Comment by FlameRaptor** [comment]
even worse in final 1.2.2

**Comment by Quicksaver** [comment]
Can you post here a screenshot please?

**Comment by FlameRaptor** [comment]
![1](https://cloud.githubusercontent.com/assets/10308169/9288581/018458c2-4380-11e5-8574-50e8d2e94490.png)

**Comment by Quicksaver** [comment]
Can you please disable all your other add-ons and themes and see if it still looks distorted like that?

**Comment by FlameRaptor** [comment]
![default](https://cloud.githubusercontent.com/assets/10308169/9288614/21b9341c-4382-11e5-9ba4-b07e672a9d32.png)
:(
all other add-ons disabled

**Comment by Quicksaver** [comment]
That's very weird, I see no reason in your screenshot for why it should look like that...

Did you also temporarily removed your userChrome.css if you have one? If you don't know what it is, you probably don't need to worry about it, but just in case you still want to check it out, it's basically a text file called userChrome.css in the "chrome" directory in your profile folder (http://kb.mozillazine.org/index.php?title=UserChrome.css).

Would you mind creating a new profile and installing only TFOB 1.2.2 in there and see how it looks? (https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles)

**Comment by FlameRaptor** [comment]
It does't make sense...After creating a new profile, it still looks like that...Nothing changed.
Perhaps I need to reinstall  firefox.

**Comment by Quicksaver** [comment]
That is the look from before version 1.2.2. Perhaps it didn't actually update the add-on, or something went wrong during the update?

**Comment by Quicksaver** [comment]
Are you using a HiDPI display?

**Comment by madmudmob** [comment]
Sorry, I am not good at techy things and do not understand ... is there something I should do to cure this please?

**Comment by Quicksaver** [comment]
- If you disable all your other add-ons and themes, does it still look like that?
- Are you using a HiDPI display?

**Comment by madmudmob** [comment]
Yes, it is the same if I disable everything else and, sorry but I have no idea what HiDiPI is so I am most probably not using it (thanks for trying to help me)

**Comment by Quicksaver** [comment]
What operating system are you on?

**Comment by madmudmob** [comment]
Windows 7 Home Premium (if that is what you are asking me)

**Comment by madmudmob** [comment]
Apologies but I have to be away from my pc for a few hours now but will check back in as soon as I can

**Comment by madmudmob** [comment]
I'm back.

Have tried uninstalling and clearing cache, history etc but when I reinstalled it is just the same.  A shame as it was the very compact look that made me download this great extension in the first place

**Comment by madmudmob** [comment]
I have reinstalled version 1.2.1 and that has got around the problem (but I do realise it's not the ideal way to go about it).  It was that or uninstall it and I have hope this will get sorted so am going to stick with this extension for now .... wait and see.

**Comment by Quicksaver** [comment]
So version 1.2.1 appears correctly in Firefox 40 but 1.2.2 doesn't?? Of all the weirdness around this issue, this definitely takes the cake... It should be the other way around...

**Comment by madmudmob** [comment]
Lol ... poor you but well done for creating the extension, it rocks!

**Comment by Quicksaver** [comment]
I'm glad you like it! :)

I just noticed, your results are a little different. FlameRaptor had the issue with 1.2.1 as well, and 1.2.2 didn't help ( @FlameRaptor just out of pure curiosity can you try to revert back to 1.2.1 and see if it stays the same?). For you @madmudmob 1.2.1 doesn't have the issue, and 1.2.2 which should fix that same issue has it...

**Comment by Quicksaver** [comment]
Hmm I have a feeling it was the OS zoom factor.

Could you try beta version 1.2.3b1 and see if that fixes the issue for you? https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/1.2.3b1

**Comment by madmudmob** [comment]
Yay!   Perfect .... thankyou soooooo much :)

**Comment by Quicksaver** [comment]
Great! :)

@FlameRaptor I'm going to presume that also fixes the problem for you. If it doesn't feel free to reopen the issue.

**Comment by FlameRaptor** [comment]
Sorry for disappearing these days.
I did use hidpi on my notebook with windows 7. Now I'am using a desktop running win XP without hidpi, and it doesn't glitch anymore. I will test on my notebook later.
Thank you so much!!
