### ISSUE TITLE
toolbar top border on windows 10

### ISSUE THREAD

**Issue by nachoijp** [Quicksaver/The-Fox--Only-Better#114]
The top border on the toolbar on windows 10 looks bad with the new appearance tweaks for FF. I managed to solve it by changing the top border width to 0 on the ClimChrome.css file for windows skin like this: 

#TabsToolbar:not([collapsed="true"]) + #theFoxOnlyBetter-slimChrome-slimmer {
		border-top: 0px solid hsla(209,67%,12%,0.35);
		position: relative;
		z-index: 1;
		margin-top: -1px;

I'm not sure if this can be easily fixed or not, I don't really mind changing it back on every update, but I think you could give it a look :)

**Comment by Quicksaver** [comment]
Could you give me a screenshot of how it looks without your fix please, so I can have some context? (I haven't tried Win10 yet.)

**Comment by nachoijp** [comment]
Sure, here you go:
![border](https://cloud.githubusercontent.com/assets/13921948/9425826/a5fb2842-48f6-11e5-8fd4-db98c2416178.png)

**Comment by Quicksaver** [comment]
Ah you mean the top border. I had no idea that border wasn't there in Win10. Yeah, I'll try to fix that for the next release so that you won't have to keep adding your code.

**Comment by nachoijp** [comment]
thanks! you're amazing, and btw, your extension made me come back to FF and I'm loving it. So thanks, twice :D

**Comment by Quicksaver** [comment]
You're welcome, twice. I'm glad you like it. :)

**Comment by Quicksaver** [comment]
Could you try out beta version 1.3b1 (https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.3b1) and see if it looks good for you? (You can still comment here even though the issue is closed.)

**Comment by nachoijp** [comment]
It works great and it looks perfect on this side, thanks!

2015-09-01 6:44 GMT-03:00 Luís Miguel <notifications@github.com>:

> Could you try out beta version 1.3b1 (
> https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.3b1)
> and see if it looks good for you? (You can still comment here even though
> the issue is closed.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quicksaver/The-Fox--Only-Better/issues/114#issuecomment-136652108>
> .
>



-- 
*Ignacio Javier Pedraza*
Córdoba, Argentina
+54 (0351) 152891527

**Comment by Quicksaver** [comment]
Great, I'm glad to hear it. Let me know if you run into any other issues.
