### ISSUE TITLE
no compatibily with 40.0.3

### ISSUE THREAD

**Issue by corbintheone** [Quicksaver/The-Fox--Only-Better#117]

**Comment by Quicksaver** [comment]
The add-on should work just fine with Firefox 40. What exactly isn't working for you?

**Comment by corbintheone** [comment]
It's trying to download The Fox Only better, and I get the message "../ it is not compatible with 40.0.3" (in french)

I am on androïd, Samsung Galaxy Tab 3 Lite.

**Comment by Quicksaver** [comment]
Issue #107, you opened that issue...

**Comment by corbintheone** [comment]
So sorry, I didn't remember my own question ... you see I really need it ! ;-)
Thanks

**Comment by Quicksaver** [comment]
To be honest I don't see how, Firefox for Android should already hide the top navigation bar when you scroll down. I don't really see anything that this add-on could do in there to improve that.

**Comment by corbintheone** [comment]
Because I would like it to be closed without doing anything : I am using it to publish a form which does not need to show anything else than itself
