### ISSUE TITLE
Allow users to disable both Skylights and mini bar

### ISSUE THREAD

**Issue by emmyemi** [Quicksaver/The-Fox--Only-Better#120]
As much as I understand the reasoning behind being unable to turn off both options, I find it quite a hassle to not be able to customize the add-on the way I prefer. I've even gone so far as to attempt to disable the Skylights individually, which still allowed me to un-check the option to show the mini bar upon surfing, but after a browser restart, the options are quickly reset.

**Comment by Quicksaver** [comment]
The reason for this is well explained in the [add-on homepage](https://addons.mozilla.org/firefox/addon/the-fox-only-better/):

> -- Important: the location bar, with the currently visited URL and the identity box next to it, provides crucial security information, to let you know that you are always where you should be and that it is safe to be there. Therefore, the add-on will not allow you to disable both the Site Identity light and the mini bar when changing locations, otherwise you won't have access to this information if the toolbars are hidden. Likewise, neither feature is needed when the navigation bar isn't included in the hidden toolbars, so they won't be enabled at all in that case.

You can easily hide the Sky Lights or the mini bar using Stylish if you really want to, it would be no different than hiding any other element in the window. But I can't provide you with a way on how to do it here (much less in the add-on itself) as I find it an important security vulnerability to allow users to do so.
