### ISSUE TITLE
Incompatibility with Dev Theme

### ISSUE THREAD

**Issue by caioems** [Quicksaver/The-Fox--Only-Better#125]
![incompatibility](https://cloud.githubusercontent.com/assets/14998541/10355902/6d75fab8-6d47-11e5-8b37-b1b6e763f73b.png)

Is there any way to make Beyond Australis work with Developer Theme?
Right now I'm using DevEdition theme enabler 1.0 on Firefox 41.0.1 and they don't see to get along.

**Comment by Quicksaver** [comment]
It should work fine with Firefox Developer Edition itself. I'm sure it's just not picking up on DevEdition theme enabler. I'll look into it soon, hopefully it'll be easy to fix.

**Comment by Quicksaver** [comment]
> Awesome, thank you for your effort. Hope it will be released soon!

In the meantime, you can try beta version 1.3.2b3 from https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.3.2b3
