### ISSUE TITLE
Addon does not work on 44.0a1 x64 Win 10x64

### ISSUE THREAD

**Issue by Nidre** [Quicksaver/The-Fox--Only-Better#128]
The Chrome is not hidden on 44.0a1 x64 (2015-10-15) Windows 10 x64. I have tried both E10's on and off. Makes no difference.

Also the Options page is blank with only search bar below which is non-functional.

![20151015 225926-win-lceh6a86523](https://cloud.githubusercontent.com/assets/6220948/10528784/6bbee4f6-7390-11e5-967a-ecc28013eb4a.png)

**Comment by Quicksaver** [comment]
#127, already fixed in the latest version 1.3.2: https://addons.mozilla.org/firefox/addon/the-fox-only-better/versions/

**Comment by Nidre** [comment]
Aha, Firefox tells me there are no updates tho. I wonder why. I will download from the link ayways, thanks for the info.

**Comment by Quicksaver** [comment]
That version is still in the queue to be reviewed. It will only update automatically once AMO's reviewers look it over and accept the update to be listed; this process is done for every new version of every add-on on AMO. ;)
