### ISSUE TITLE
Hope to add an option to close the add to bookmark button on mini bar

### ISSUE THREAD

**Issue by FlameRaptor** [Quicksaver/The-Fox--Only-Better#132]
Hi，
    I really don't like this new feature in version in 1.3, because it makes the mini bar no longer mini.I like the older 1.2 style mini bar. So if you have some spare time, please consider adding this option. And thank you for making this excellent add-on.

**Comment by FlameRaptor** [comment]
You gave it a bug label well, I don't think it's a bug. It's just something a little bit imperfect. Thank you for your changing, and I will enjoy the new version. :)

**Comment by Quicksaver** [comment]
I consider it a bug because I wanted to do this from the start but forgot to do it. :)
