### ISSUE TITLE
Using Beyond Australis together with Tab Tree and Windows 7's Min/Max/Close buttons 

### ISSUE THREAD

**Issue by KitsuneRale** [Quicksaver/The-Fox--Only-Better#133]
Good day. I have the following combination: Windows 7, Firefox (Developer Edition and Release - no difference) with Beyond Australis and Tab Tree. The two extensions help to give me as much vertical space as physically possible; however, there's one inconvenience. When a window is maximized, Tab Tree removes the title bar and stuffs the system buttons (Minimize/Restore/Close) into the address/toolbar instead. If I add Beyond Australis and turn Slim Chrome on, the system buttons disappear. They are still there (I can blindly minimize a window, e.g.) but they are not displayed.
![tabtreebeyondaustralis](https://cloud.githubusercontent.com/assets/10569730/11269770/a0ae89be-8efc-11e5-8ea5-04926e842839.png)

I understand that my combination is rare (possibly unique) so I will understand if I'm ignored with my petty troubles. But I'd really appreciate (and willing to pay up for the effort) if you could fix this. If I'd better approach the Tab Tree author, please say so.

**Comment by Quicksaver** [comment]
I do see this issue, but the thing is I see a lot of display weirdness with only Tab Tree installed, such as lots of elements not being repainted properly (tabs not updating, location bar not showing newly typed characters, etc). I'm sure this issue has to do with that, as in it's failing to repaint those buttons, and a whole lot of other things.

Do you not have those issues?

**Comment by KitsuneRale** [comment]
You might have stumbled over problems with hardware acceleration - Tab Tree doesn't get along with Firefox's usage of hardware acceleration on Intel cards, for some reason. Switching it off removes almost all painting problems but not this one.




On Thu, Nov 19, 2015 at 2:33 PM -0800, "Luís Miguel" <notifications@github.com> wrote:












I do see this issue, but the thing is I see a lot of display weirdness with only Tab Tree installed, such as lots of elements not being repainted properly (tabs not updating, location bar not showing newly typed characters, etc). I'm sure this issue has to do with that, as in it's failing to repaint those buttons, and a whole lot of other things.



Do you not have those issues?

**Comment by traxium** [comment]
Tab Tree 1.3.8, Beyond Australis 1.3.4, Windows 7 x64 (Virtual Box), FF 42.0 and 42.0a2. I don't have the issue:
![beyondaustralis](https://cloud.githubusercontent.com/assets/13660441/11342384/2eefadfc-9218-11e5-9ee7-a4720d8f9874.png)
![beyondaustralis - full width](https://cloud.githubusercontent.com/assets/13660441/11342388/32a71e94-9218-11e5-81c0-6c4cf5214ef5.png)
![beyondaustralis - dark](https://cloud.githubusercontent.com/assets/13660441/11342545/fa0b219c-9218-11e5-840a-6f5204be0e77.png)
![beyondaustralis - dark - full width](https://cloud.githubusercontent.com/assets/13660441/11342547/fc45a9be-9218-11e5-8204-0c69ba6276da.png)

**Comment by Quicksaver** [comment]
I'm not sure about @KitsuneRale but I definitely have the issue in Firefox 64bit, both release and dev. edition.

**Comment by traxium** [comment]
Ok, I just tested it in real Windows 7 x64. It worked when I used "no-aero" theme:
![beyondaustralis - real](https://cloud.githubusercontent.com/assets/13660441/11343534/859ba5a2-921d-11e5-859b-633f3fea1f6d.png)
But there were issues when I used "aero" themes:
![beyondaustralis - real - glass](https://cloud.githubusercontent.com/assets/13660441/11343569/b0338fd2-921d-11e5-943c-60bd4047d161.png)
![beyondaustralis - real - glass - compact](https://cloud.githubusercontent.com/assets/13660441/11343582/b6d0a7c6-921d-11e5-981a-5abc5de5c13f.png)
![beyondaustralis - real - glass - full width](https://cloud.githubusercontent.com/assets/13660441/11343585/ba5a5aea-921d-11e5-9fae-66f9849328c0.png)

**Comment by Quicksaver** [comment]
Indeed, if I disable aero I don't see the problem either. By the way, I don't see the exact same issue as in those screenshots, my buttons are completely invisible just like reported originally. Either way, my patch should fix all of it. :)

**Comment by traxium** [comment]
After the patch it looks like this (not hovered, "aero"):
![beyondaustralis - real - after pr - dark](https://cloud.githubusercontent.com/assets/13660441/11344935/3ca73034-9225-11e5-819e-afab20bffd0c.png)
Hovered ("no aero"):
![beyondaustralis - after pr - hovering](https://cloud.githubusercontent.com/assets/13660441/11345066/f4990064-9225-11e5-9044-7208af34ac66.png)
I think it's not the desirable result?

**Comment by Quicksaver** [comment]
It is, the patch moves the buttons container to the top right corner outside of the nav-bar, where the physical buttons actually are. They would never work in the hidden toolbars because the toolbars are position:fixed above the content, and AFAIK there's no way to move the actual buttons there.

You have to remember that the container that tab-tree moves to the nav-bar is only a "see-through window" to the actual buttons; the actual buttons are controlled by the operating system, and I believe they can't be hidden or moved. So they have to always remain at the corner like that.

It's not the most visually appealing layout, but at least to my knowledge it's the only way to make it work like this. :( Unless you know how to move/hide the actual buttons, or have any other idea?

**Comment by traxium** [comment]
As it seems the actual minimize/restore/close buttons can be moved/hidden only in Windows 7 if "aero" is disabled (and in Windows XP). I haven't found a way to move/hide them in Windows 8.
By the way, the similar result could've been achieved with the "browser.tabs.drawInTitlebar=false" about:config option:
![beyondaustralis - real - drawintitlebar](https://cloud.githubusercontent.com/assets/13660441/11346087/f17c43a4-922b-11e5-9ff5-99b716b428bc.png)

**Comment by Quicksaver** [comment]
> By the way, the similar result could've been achieved with the "browser.tabs.drawInTitlebar=false" 

Indeed. :)

**Comment by KitsuneRal** [comment]
Thanks for the investigation, guys. Unfortunately,
browser.tabs.drawInTitlebar=false doesn't work for me because I really
appreciate the feature with hitting the top edge of the screen with my
mouse and have the address bar falling out thanks to Beyond Australis.
Besides, I really like the amount of vertical space consumed by chrome
(virtually nothing) when the titlebar is hidden. The patch from Luís
(judging by the screenshots) still gives a smaller margin that an ordinary
titlebar - if the whole margin is sensitive for Beyond Australis, it'd be
still quite better than just not hiding the titlebar.

**Comment by traxium** [comment]
The new thick margin behaves like the old thin margin.

**Comment by Quicksaver** [comment]
Yes it does. I'm sorry, I meant to have replied earlier but forgot. The top margin will behave exactly the same as before, except it's now taller.

**Comment by Quicksaver** [comment]
Let me know if you still have issues once the next version of Tab Tree is released. :)

**Comment by KitsuneRal** [comment]
I'm not sure how much you spent on this, so my contributions are arbitrary.
Thanks for making this happen guys.
