### ISSUE TITLE
It's hard to display the window in full screen when enable Slim Chrome (Style: Compact)

### ISSUE THREAD

**Issue by zz55** [Quicksaver/The-Fox--Only-Better#134]
Hello everyone, I install Beyond Australis addon and enable: Slim Chrome, Style: Compact
http://i.imgur.com/yK6Yk5B.png

But when press F11 to display the window in full screen -> the screen appears a line (8 pixel height) at the top (if select Hide the navigation bar), the screen appears address bar (if don't select Hide the navigation bar),
http://i.imgur.com/6k1zuKI.png
http://i.imgur.com/Bf9YnMg.png

When disable Beyond Australis or choose other Style -> the window backs to normal
http://i.imgur.com/jfMbfvY.png

Is there any way to make that line or address bar don't appear when press F11 to display full screen? (I use Firefox 42, Windows 7). Sorry for my bad English if there are mistakes. Thank you for reading

**Comment by Quicksaver** [comment]
There's something wrong going on there. Slim Chrome should disable itself while in fullscreen (if you have the option "Hide toolbars" enabled, you can check by right clicking them while in fullscreen). But it's obviously not happening. Can you please try disabling all your other add-ons except for Beyond Australis and see if that still happens?

**Comment by zz55** [comment]
Thank you for your support. I followed your instruction but the bug haven't disappeared yet, sometimes it's auto disappear (I don't know why) but now it still there, every press F11 I have to move the mouse cursor in-out-in-out... to go to full screen, video: 
https://youtu.be/7PnvCjGPyyQ
The bug only happens when choose style Compact

**Comment by Quicksaver** [comment]
I'm sorry for the delay in getting to this. Is this still happening with the latest version of Firefox 43 and Beyond Australis 1.3.4.1?

**Comment by ewdm** [comment]
Have the same issue. Tried disabling other addons, but it didn't help.
Beyond Australis 1.4.4.
Firefox 45.0.

**Comment by bhabba** [comment]
I'm experiencing the same issue. After enabling full screen mode (F11) the Slim Chrome doesn't seem to be disabled immediately. Most of the times after entering full screen mode the navigation toolbar stays visible for some time during which I can't access the tab bar. It's the same misbehavior as in @zz55's youtube clip.

***

Slim Chrome enabled; Also hide the navigation bar enabled; Style: Australis; Animation: None
Beyond Australis 1.4.4
Firefox 45.0
Ubuntu 14.04 LTS x64

**Comment by Quicksaver** [comment]
Can you tell if this happens in a clean profile? https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by bhabba** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [16. März 2016, 18:05 MEZ](https://github.com/Quicksaver/The-Fox--Only-Better/issues/134#issuecomment-197428400 "2016-03-16T17:05:32Z - Replied by Github Comment Enhancer"):
> Can you tell if this happens in a clean profile? [https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles)

I've just tested it with a clean profile (only extension installed: Beyond Australis). Exactly the same misbehavior as before.

**Comment by Quicksaver** [comment]
Can you try [beta version 1.4.5b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.5b1) and let me know if it makes any difference? I still can't reproduce this locally, so I tried a small "blind" fix. I'd like to know how close, or far, I am from the cause.

**Comment by bhabba** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [17. März 2016, 13:55 MEZ](https://github.com/Quicksaver/The-Fox--Only-Better/issues/134#issuecomment-197866865 "2016-03-17T12:55:06Z - Replied by Github Comment Enhancer"):
> Can you try [beta version 1.4.5b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.5b1) and let me know if it makes any difference?

Looks pretty good, I can't reproduce the issue anymore with v1.4.5b1 :thumbsup:
To be sure maybe others should test the beta version as well...

**Comment by ewdm** [comment]
Thanks, the beta version resolves the issue now.
