### ISSUE TITLE
Toolbar with GiT's Hinge Effect is hidden by interactive website content (e.g. Flash).

### ISSUE THREAD

**Issue by DaCoolboy** [Quicksaver/The-Fox--Only-Better#135]
Even if the animation completes, it still gets overlayed long as GiT's Hinge Effect is enabled.
Happens since a few updates.
![git s hinge effect bug](https://cloud.githubusercontent.com/assets/2771553/11684679/b446bcc2-9e73-11e5-95d9-120cab20733a.png)

**Comment by Quicksaver** [comment]
Damn, I guess this is back... Unfortunately there is no easy fix right now, I will have to wait for e10s to be released to rewrite the way the styles (and animations) are done, to avoid issues like these. See issue #95 for more information.

**Comment by DaCoolboy** [comment]
Seems fixed, closing.

**Comment by DaCoolboy** [comment]
Seems no longer the case, closing.
