### ISSUE TITLE
Sky Lights "bleed" through Fullscreen

### ISSUE THREAD

**Issue by DaCoolboy** [Quicksaver/The-Fox--Only-Better#136]
In the top-left corner Sky Lights are slightly visible, as seen in the red ellipse
 .
Though this is probably a minor issue.
They are even clickable.

At first I thought my screen was broken.
![skylightsbleedthrough](https://cloud.githubusercontent.com/assets/2771553/11698325/4c6d396e-9ebe-11e5-80e5-df60adbdced6.png)

**Comment by Quicksaver** [comment]
You're right, that's not supposed to happen of course. Thanks for letting me know, I'll try to fix it for the next update.
