### ISSUE TITLE
Folders disappear in the bookmarks bar

### ISSUE THREAD

**Issue by flacoclau** [Quicksaver/The-Fox--Only-Better#137]
As the title says, these folders are not visible. If I disable the plugin, they appear, or if i enable the add
again,  then also appear. But if I close the browser and open it again, the problem returns. I'm using version 1.3.4.1, Mozilla 42.0 on Linux Mint 17.3.
Greetings from Cordoba city, Argentina.

**Comment by Quicksaver** [comment]
What do you mean when you say "if you enable the add again"?

Could you please try disabling all your other add-ons except for Beyond Australis and see if the problem still persists?

**Comment by flacoclau** [comment]
With the other complements disabled, the problem persists.

Im sorry, im not english-speaking. I mean that once it appeared again the folders and enable "BEYOND AUSTRALIS" complement, these folders are still on the bar.

1. I open the the browser and the folders can not be seen in the bar
![1](https://cloud.githubusercontent.com/assets/16249186/11743757/caed13a6-9fe8-11e5-8a79-509a1757d03f.png)


2. I Disable the add "BEYOND AUSTRALIS", the folders appears!!
![2](https://cloud.githubusercontent.com/assets/16249186/11743565/479f9ab0-9fe7-11e5-9540-fd3fa3ac6ec3.png)

3.Then if i Enable the add "BEYOND AUSTRALIS" the folders still im the bar
![3](https://cloud.githubusercontent.com/assets/16249186/11743738/949e82d0-9fe8-11e5-84f1-a22d026a8e78.png)

**Comment by Quicksaver** [comment]
Hmm is this still happening for you with Firefox 43? I still can't reproduce it locally.

**Comment by flacoclau** [comment]
Now its working fine, in this moment i have Linux Mint 17.3 and Mozilla 43

**Comment by Quicksaver** [comment]
Ok, let me know if it ever happens again.

**Comment by flacoclau** [comment]
Thanks!
