### ISSUE TITLE
Buttons are to big since update

### ISSUE THREAD

**Issue by Orlff** [Quicksaver/The-Fox--Only-Better#138]
Since the update the buttons are way to big. Is there a way to make them smaller? Thank you.

**Comment by Quicksaver** [comment]
What buttons?

**Comment by Orlff** [comment]
I use firefox and the extension add-ons are shown in the form of a button.

**Comment by Quicksaver** [comment]
This page is for support for my add-on called Beyond Australis. Is this somehow related? I'm not sure I follow.

**Comment by Orlff** [comment]
I am using the add-on Beyond Australis.

**Comment by Quicksaver** [comment]
I figured, but does it affect your buttons? As in if you disable it is there any difference?

**Comment by Orlff** [comment]
I took a screenshot (Hope this shows up. ![thu-12-17-2015 beyond australis](https://cloud.githubusercontent.com/assets/16343287/11885675/ac72bf78-a4ef-11e5-97d0-435ec9d8965f.jpg)

**Comment by Quicksaver** [comment]
That big "b" button stands out, it could be stretching the others. But you still haven't mentioned if everything goes back to normal if you disable Beyond Australis.

**Comment by Quicksaver** [comment]
(or if you disable just Slim Chrome)

**Comment by Orlff** [comment]
The buttons are only in the Australis menu. 
![australis extension not shown](https://cloud.githubusercontent.com/assets/16343287/11885758/806024b0-a4f0-11e5-8eac-ee4f4335d147.jpg)
![australis extension shown](https://cloud.githubusercontent.com/assets/16343287/11885764/9248fcce-a4f0-11e5-8815-ada9b9bb7819.jpg)

**Comment by Quicksaver** [comment]
I understand, but if you disable Beyond Australis (open the Add-ons Manager and try disabling it) do your buttons still look like that?

**Comment by Orlff** [comment]
If I disable Australis nothing shows up. The buttons are only on the Australis menu.

**Comment by Quicksaver** [comment]
By "disable" I don't mean hide the toolbars (or menu as you call it), I mean you should go to the add-ons manager by either pressing Ctrl+Shift+A or going to the menu Tools -> Add-ons and actually disable the add-on. The toolbars should always be visible then, they shouldn't be hidden at all; if they are that's a whole other thing. Are the buttons still big like that when the add-on is disabled?

**Comment by Orlff** [comment]
OK, I disabled Australis and the buttons still look the same so I guess it is a firefox thing.

**Comment by Quicksaver** [comment]
That's what I thought, as the add-on really doesn't touch the button styling at all. ;) I suggest you start with whatever is giving them that rounded 3d look.

**Comment by Orlff** [comment]
OK, thank you so much for taking the time.

**Comment by Quicksaver** [comment]
Don't mention it. :)
