### ISSUE TITLE
Since FF 44, the fox only better préferences panel is no longer accessible

### ISSUE THREAD

**Issue by cybermarmotte** [Quicksaver/The-Fox--Only-Better#141]
The title is self explained, Since FF 44, the fox only better préferences panel is no longer accessible

Anyway, we can wait, your work is amazing

**Comment by Quicksaver** [comment]
It works fine for me. Is your version updated? I ask because it's called Beyond Australis now.

**Comment by cybermarmotte** [comment]
See

https://www.evernote.com/l/ABLMyiFku_BJy7LWG1f0xHIybYa97Mc1HKU

**Comment by Quicksaver** [comment]
I meant the add-on, the latest version is 1.3.4.1-let-fixed, but I'll assume that's what

Can you do a small test for me please, close the add-on's preferences tab, open the browser console (Cmd+Shift+J), clear it, then try to open the the preferences tab again. Did anything appear in the console?

**Comment by Quicksaver** [comment]
(The last message was incomplete.)

I meant the add-on, the latest version is 1.3.4.1-let-fixed, but I'll assume that's what you have. Does the same happen if you disable all your other add-ons except for Beyond Australis?

Can you do a small test for me please, close the add-on's preferences tab, open the browser console (Cmd+Shift+J), clear it, then try to open the the preferences tab again. Did anything appear in the console?

**Comment by cybermarmotte** [comment]
I updated the evernote note with some console informations. The workaround was deactivated the add-on removed it and installed it again, it's working fine now.

**Comment by Quicksaver** [comment]
That evernote link isn't valid anymore.

**Comment by cybermarmotte** [comment]
How, I'm sorry, here it is: https://www.evernote.com/l/ABJy-xQGfSJGSYSpi-ROkubERSWBcBUAs-M

It changed as I merged some other notes.

**Comment by Quicksaver** [comment]
You are using an old version of the add-on. Please update to the latest version and try again as that version won't work with Firefox 44 at all, but that incompatibility has been fixed since in the later versions.

You can update by going to your add-ons manager and check for updates there (the gear button at the top), you should also keep "Update add-ons automatically" enabled in there to prevent this from happening again, unless of course you have a reason not to.

Please let me know if after updating that still happens.

**Comment by cybermarmotte** [comment]
Its checked but for a reason I don't know it didn't. Be sure I checked for updates before filling this issue. Deleting and installing fixes this outdated problem, see https://www.evernote.com/l/ABLrMlmH-VBNkqCpoUEvW5DPhaNhiFywya8

**Comment by Quicksaver** [comment]
Great, as long as it's working now. :) Let me know if it ever happens again.
