### ISSUE TITLE
Search bar icons are disproportionately large and blurry

### ISSUE THREAD

**Issue by MOFTAD** [Quicksaver/The-Fox--Only-Better#147]
I love the new awesome bar update (it means that I don't have to use the outdated Omnibar add-on anymore), but I've noticed that the search icons are blurry and overly large. I'm not sure if this is a problem with Firefox or your add-on since, as mentioned, I had the default search hidden since I was using Omnibar. Note that I have tested this with all other add-ons/styles/scripts disabled.

See [here](http://i.imgur.com/UFhzj9z.png).

While I'm on the topic, would it be possible to add an option to merge the search bar and URL bar but without the search icons at the bottom? That's how it worked with Omnibar and it was best for me since I tend to rely on keywords anyway.

**Comment by Quicksaver** [comment]
> I love the new awesome bar update (it means that I don't have to use the outdated Omnibar add-on anymore)

I'm glad you like it. This is actually one of the reasons that made me do this, my Omnibar hasn't been performing very well either these last few months. :)

> the search icons are blurry and overly large

Already fixed and uploaded fixed version to AMO, give it a day or two and it should update automatically. :)

> While I'm on the topic, would it be possible to add an option to merge the search bar and URL bar but without the search icons at the bottom? That's how it worked with Omnibar and it was best for me since I tend to rely on keywords anyway.

You could just [uncheck all your one-click search engines](https://support.mozilla.org/kb/add-or-remove-search-engine-firefox#w_hide-search-engines). That way it will hide all icons (or just a few of them if you want) but keep their search words which you can still use in the location bar. Let me know if this is not the best solution for your use-case, although I'm betting it will be more than enough.
