### ISSUE TITLE
Allow to navigate through search engines using keyboard when using "Show search engines in the location bar"

### ISSUE THREAD

**Issue by liljaylj** [Quicksaver/The-Fox--Only-Better#150]

**Comment by Quicksaver** [comment]
[It's right there in the homepage: ;)](https://addons.mozilla.org/firefox/addon/the-fox-only-better/)

> - You can right-click a search engine, or use Ctrl+Up and Ctrl+Down on your keyboard (Command+Up and Command+Down on Mac), to define another search engine to be used by default until you select another one.

**Comment by liljaylj** [comment]
Thanks for quick reply, and sorry for inattention (wall of text on home page). And one more question: Could I somehow preserve my last search query in awesomebar (just in case if i want use one to search through another search engine)? It's really cool to search via location bar hiding search panel (saves lot of space) and it will be great if could reuse my search query.

**Comment by Quicksaver** [comment]
It's no problem of course, that's why I'm here. :)

If you're using the adaptable search bar, the word you searched for should appear in it when you're on the results page of that search.

For instance, if you search google for "me", when you're in the google results page the search bar should appear next to the location bar with the word "me" in it. Then you just have to click it, and it will take you to the location bar as if you had clicked there, except it will paste the word "me" there and you'll be able to use it with another engine immediately.

**Comment by liljaylj** [comment]
Yes, I know that and it's functioning great. The issue is that adaptable search bar supports only limited number of predefined SEs. But I have some third party SEs when using which I unfortunately lose my query. Just as a suggestion, adaptable search could preserve the query when search from location bar invoked by any SE option, then (maybe) hide when user change location.
Sorry, for my terrible english

**Comment by Quicksaver** [comment]
I have been thinking about that, but unfortunately I wasn't able to come up with a proper way to do it for this release. But it is on my to-do list.

In the meantime, if there are any search engines you'd like me to try to add support for the adaptable search bar, just let me know. :)

**Comment by liljaylj** [comment]
It's good to know that this feature on your roadmap :) I try to fork and contribute to your project. It may happen that I can help you somehow (never developed add-ons for Firefox. It's time to learn something new, I guess ;) )
And as for SEs I use, they are most likely niche, associated with the region where I live (CIS) and the Linux distro that I use (ArchWiki, Arch Packages and AUR).
Thank you for responsiveness, Quicksaver. Good Luck!
