### ISSUE TITLE
Compatibility with Search Site extension

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/The-Fox--Only-Better#152]
It was broken since the search bar into urlbar. I'm not sure who is more suited to make a shim.

It is the only obstacle to accept the new interface for me.
You can contact its author via email on https://addons.mozilla.org/firefox/addon/search-site/.

**Comment by Quicksaver** [comment]
I contacted the Search Site's dev to see what's the best way to tackle this. I'm guessing its icon will somehow have to be shown in the location bar in these conditions, but I don't think this is something I can do from my side alone. But hopefully we'll be able to do something about it soon somehow.

In the meantime, Search Site actually still works, for instance you can right click a word anywhere in the page and you still have its option in the context menu. And you can also disable "Show the search bar only when it's not empty" in Beyond Australis preferences to show the search bar and it should still work as well.

**Comment by yfdyh000** [comment]
Thanks for your touch, I hope this is a perfect partnership.
Yes, I disabled the new interface with the option to keep the search bar temporary.

**Comment by Quicksaver** [comment]
For now I've made it so the Search Icon is visible in the location bar in the same (or almost the same) conditions that it would appear in the search bar. Please give [beta version 1.4.4b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.4b1) a try and let me know how it works for you.

Note that only the icon itself is visible in the location bar. There are no Search Site options by right-clicking the suggestions or the search engine's icons and any other of those extras. I'm afraid those will be extremely difficult to accomplish, even by Search Site itself if/when its developer adds native support for the location bar. Simply put, the location bar's panel really doesn't handle context menus and outside click handlers very well... I hope that for now that icon will be enough as there's not much else I can do only on my side.

**Comment by Quicksaver** [comment]
(Of course this only happens with the preference "Show the search bar only when it's not empty" enabled, it wouldn't make much sense otherwise.)

**Comment by yfdyh000** [comment]
Looks works, although it is not a perfect interface design. It is because the longer width lead to a distant and inconspicuous icon.

An immature proposal, if we support drag and drop any toolbar icons to the address bar suggestion list in Customize, such as the position of search engine icons list. However, the Search Site icon looks is not a standard toolbar icon, it can not be dragged in Customize.
In that case, I can accept this interface, this issue can be marked as fixed. Thank you for your efforts.

**Comment by Quicksaver** [comment]
> it is not a perfect interface design. It is because the longer width lead to a distant and inconspicuous icon.

True, but then if you install Search Site then you should expect that icon to be there. It's not like it will appear for unsuspecting users who have no idea what it is. ;)

> if we support drag and drop any toolbar icons to the address bar suggestion list in Customize, such as the position of search engine icons list. However, the Search Site icon looks is not a standard toolbar icon, it can not be dragged in Customize.

It's not a standard toolbar button indeed, it would be up to Search Site itself to implement it as such, here I'm just copying what it already does for the search bar.

And at the moment dragging buttons to the suggestions panel area isn't in the plans to be honest, it's not as easy to implement as it sounds (although it's not a bad idea for [Puzzle Bars](https://addons.mozilla.org/firefox/addon/puzzle-toolbars/)), but I haven't run across that many add-ons with toolbar buttons that deal specifically with location-bar / input-url-or-word related actions. So I'm not sure the gain there would be a lot either.

**Comment by yfdyh000** [comment]
I have seen many times, the Search Site icon may not appear sometimes if Ctrl+V to urlbar.
The Search Site icon is set to Autohide. Some events may not be triggered.

**Comment by Quicksaver** [comment]
Indeed, there are a few special cases I didn't notice last time. Let's see what I can do about it.

**Comment by Quicksaver** [comment]
Care to try [beta version 1.4.4b2](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.4b2)? :)

**Comment by yfdyh000** [comment]
Looks fixed, rapid responsive always. Thanks.
