### ISSUE TITLE
Minibar close too early sometimes

### ISSUE THREAD

**Issue by EMLVIRUS** [Quicksaver/The-Fox--Only-Better#157]
Minibar should not disappear until pages are fully loaded if "surf to another location" box on about:thefoxonlybetter#slimChrome is checked.
This is helpful in redirecting. If your network connection is slower, minibar disappears before you know where you are going, hence security risk.

**Comment by Quicksaver** [comment]
If there is a redirect, the mini bar will appear again, so there's no risk there, at least not one that keeping the mini bar open for a longer period of time would mitigate.

If the network connection is slower and the page takes a longer time to load, you would simply end up with a static mini bar in there that would be telling you nothing more than you already know. Maybe I'm missing something here, but I don't see what you would gain with this at all. Can you elaborate a little please?

**Comment by EMLVIRUS** [comment]
I may give two specific examples here (maybe Ive missed somethin' b4):
1. If you have [Location Bar Enhancer](https://addons.mozilla.org/en-US/firefox/addon/ui-enhancer/), yr URL will "spread out" as animation effects instead of displaying all at once. Minibar has chance to close b4 you see all URL or even complete domain. So you need minibar stays longer.

**Comment by EMLVIRUS** [comment]
2. In China (maybe **ONLY** in China), many web contents are from third party. For example, on LOL China site, this: http://lol.qq.com/v/go.shtml?id=22853&type=lwvideo&url=http://v.longzhu.com/520/v/499214?from=lolclient&e_code=lolweb.videoauthorindex.authornew.
Clearly lol.qq.com is not true domain where the video comes from, but longzhu.com. Sometimes Clean Links can handle such links but not all or, more accurately, not often. So you need Longer minibar in China.
PS China is an **_AMAZING_** place.

**Comment by Quicksaver** [comment]
> i. If you have Location Bar Enhancer, yr URL will "spread out" as animation effects instead of displaying all at once. Minibar has chance to close b4 you see all URL or even complete domain. So you need minibar stays longer.

True, but that's not the only problem when using this together with Location Bar Enhancer. It's also impossible to control LBE from the outside (from withing Beyond Australis for instance) so this is not something that's easily fixed. Simply increasing the time the mini bar stays shown is not a fix for this; at most it's a band aid. You can use [Status-4-Evar](https://addons.mozilla.org/firefox/addon/status-4-evar/) to show the progress meter in the location bar, and it will keep the mini bar shown for as long as the progress meter isn't finished (until the page loads).

I have wanted to write my own segmentation feature into the add-on for a while, to cover for the faults with using Location Bar Enhancer together with Slim Chrome, I just haven't had the time to do it yet.

> Plus, even you have Location Bar Enhancer to show the ending part of URL, sometimes the starting part is true domain, hence inconvenience.

Precisely, another fault with Location Bar Enhancer which I can't control from my side.

> ii. In China (maybe ONLY in China), many web contents are from third party. For example, on LOL China site, this: http://lol.qq.com/v/go.shtml?id=22853&type=lwvideo&url=http://v.longzhu.com/520/v/499214?from=lolclient&e_code=lolweb.videoauthorindex.authornew.
Clearly lol.qq.com is not true domain where the video comes from, but longzhu.com. 

The location bar shows you the location to whatever page you're on, in that case the page really is in lol.qq.com. It just so happens that page is set up to use frames directing somewhere else. The fact that that particular url has the frame's location in it is just convenience I guess, there are dozens of examples of similar pages in frames that don't show the "true" location in the location bar.

This is not something this add-on can resolve at all, much less something that I would implement to "disguise" the fact that you're on a page with frames.
