### ISSUE TITLE
Location Bar Puzzle Bar support

### ISSUE THREAD

**Issue by EMLVIRUS** [Quicksaver/The-Fox--Only-Better#159]
If you enable Location Bar in Puzzle Bar, it should be supported in minibar. Complete toolbar should not be displayed when you move mouse over Location Bar for buttons.

**Comment by Quicksaver** [comment]
I don't understand, the icons in the Location Bar's Puzzle Bar shouldn't appear in the mini bar at all. Are they appearing for you?

**Comment by Quicksaver** [comment]
Please reopen if you can add more info.
