### ISSUE TITLE
Search suggestions in Awesome Bar (Location Bar) don't work with other search engines

### ISSUE THREAD

**Issue by bhabba** [Quicksaver/The-Fox--Only-Better#163]
I've enabled the options `When using the location bar, provide ... Search suggestions` as well as `Show search engines in the location bar`. Now if use the auto-completion feature (aka "search suggestions") from my default search provider (DuckDuckGo) **and then search for that term with another search engine** like Wikipedia **it doesn't properly work** because not only the string I want to search for is submitted to Wikipedia but also a whole bunch of information related to the DuckDuckGo search engine.

Example:
I want to search for the term "gini coefficient". After I've entered "gini " I ~~click on~~ _select_ the corresponding search suggestion "gini coefficient" (obviously coming from DuckDuckGo) _with the arrow keys of my keyboard_ and then click on the search engine button for Wikipedia. Now instead of just "gini coefficient" this whole string gets filled in Wikipedia's search engine :
`moz-action:searchengine,{"engineName":"DuckDuckGo","input":"gini coefficient","searchQuery":"gini","searchSuggestion":"gini coefficient"}`

This also manifests in the loaded Wikipedia URL: `https://en.wikipedia.org/w/index.php?title=Special:Search&search=moz-action%3Asearchengine%2C{%22engineName%22%3A%22DuckDuckGo%22%2C%22input%22%3A%22gini+coefficient%22%2C%22searchQuery%22%3A%22gini%22%2C%22searchSuggestion%22%3A%22gini+coefficient%22}`

**Comment by Quicksaver** [comment]
>  After I've entered "gini " I click on the corresponding search suggestion "gini coefficient" (obviously coming from DuckDuckGo) and then click on the search engine button for Wikipedia.

How do yo uclick on the corresponding search suggestion without searching immediately DuckDuckGo for it?

**Comment by bhabba** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [17. März 2016, 13:03 MEZ](https://github.com/Quicksaver/The-Fox--Only-Better/issues/163#issuecomment-197848575 "2016-03-17T12:03:52Z - Replied by Github Comment Enhancer"):
> How do you click on the corresponding search suggestion without searching immediately DuckDuckGo for it?

Ah sorry, my mistake. I actually didn't "click" but selected the search suggestion with the arrow keys of my keyboard.

**Comment by Quicksaver** [comment]
Can you please try [beta version 1.4.5b2](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.5b2) and confirm that it fixes the issue for you?

**Comment by bhabba** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [23. März 2016, 13:07 MEZ](https://github.com/Quicksaver/The-Fox--Only-Better/issues/163#issuecomment-200323576 "2016-03-23T12:07:40Z - Replied by Github Comment Enhancer"):
> Can you please try [beta version 1.4.5b2](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.5b2) and confirm that it fixes the issue for you?

Just did, everything works fine now. Thank you very much!
