### ISSUE TITLE
Broken in latest nightly

### ISSUE THREAD

**Issue by vyvl** [Quicksaver/The-Fox--Only-Better#166]
Addon doesn't work in latest nightly. 

- Slim chrome doesn't work. 
- Opening addon config page shows blank page. 
- Url suggestions shows titles but doesn't have fav icons or url in it .

**Comment by Quicksaver** [comment]
> Opening addon config page shows blank page. 

This I've already fixed. But I can't reproduce any of the other issues. Can you please try [beta version 1.4.5b2](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.5b2) and see if it's still happening?

**Comment by vyvl** [comment]
They are disabled in configuration, since the config page is not working, I assumed slim chrome is not working. It is fixed now. Thanks.
