### ISSUE TITLE
Adaptable search bar doesn't work correctly

### ISSUE THREAD

**Issue by bhabba** [Quicksaver/The-Fox--Only-Better#167]
I've noticed that the "adaptable search bar" feature doesn't work as supposed. 

If I search for a term with a supported search engine (like DuckDuckGo) the search bar becomes visible and is correctly synchronized with my web search after the results page is loaded, and when I click on the search bar the focus is brought to the Awesome Bar (location bar) with the search term copied over – so until this point everything is fine.

But **if try to search for that term with another search engine** (pressing the down arrow key of my keyboard to open the panel with the suggestions and search engine entries and clicking on the Wikipedia entry for example) **the search term doesn't get submitted to the other search engine, i. e. no actual search is performed**, just an empty results page or (depending on the search engine) the homepage of the search engine is loaded. Only if I modify the search term (like adding a space) beforehand the search is performed correctly.

The problem also occurs with a clean profile (only extension installed: Beyond Australis; default settings).

***

Beyond Australis 1.4.4
Firefox 45.0
Ubuntu 14.04 LTS x64

**Comment by Quicksaver** [comment]
Well noticed. [Beta version 1.4.5b3](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.5b3) should fix that. Would you mind trying it out and letting me know how it works?

**Comment by bhabba** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [24. März 2016, 18:37 MEZ](https://github.com/Quicksaver/The-Fox--Only-Better/issues/167#issuecomment-200942896 "2016-03-24T17:37:56Z - Replied by Github Comment Enhancer"):
> Would you mind trying it out and letting me know how it works?

Works like a charm! Thanks for fixing this so quickly!

**Comment by Quicksaver** [comment]
No problem, I'm glad to hear that. :)
