### ISSUE TITLE
Bookmark Sky Light Color Does Not Switch Anyway

### ISSUE THREAD

**Issue by EMLVIRUS** [Quicksaver/The-Fox--Only-Better#169]
(On Firefox 46 beta)
Bookmark Sky Light color does not switch to blue when you are on a bookmarked page.
The color even won't switch when you bookmark a page by clicking the Sky Light.

**Comment by Quicksaver** [comment]
Already fixed by 94813cd0ab6bc15e89878904c5e33b191a52a3cb. You can give [beta version 1.4.5b3](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.5b3) a try if you want to confirm that it's fixed for you as well.
