### ISSUE TITLE
The toolbar thet drops down has  a transparent background.

### ISSUE THREAD

**Issue by rrvau** [Quicksaver/The-Fox--Only-Better#171]
The Firefox toolbar that drops down contains the Bookmarks Toolbar and below it, the Firefox Toolbar (containing "Home", "Search" etc.) which has a tranparent background.
a: How ca I make the background solid again?

b: How can I position this toolbar above the Bookmark Toolbar?

Thanking you in advance,

Royce

**Comment by Quicksaver** [comment]
I don't fully understand, can you attach a screenshot please? Nothing should be transparent.
