### ISSUE TITLE
Suggestion: Make the Seperator between the Top and Content clickeable to show the browser bar

### ISSUE THREAD

**Issue by EuphoricEuler** [Quicksaver/The-Fox--Only-Better#172]
Sometimes I'm bothered by the fact that I need to hoover over the top for some time to make the chrome appear. I would prefer if the seperator was just clickable to show the browser bar instantly.

**Comment by Quicksaver** [comment]
You can define the sensitivity in the preferences. If you set it to the highest setting and use the "no animation" option, it should show instantly. There's really no more improving than that. Is this not happening for you with those settings?

**Comment by EuphoricEuler** [comment]
Hi Luis,

thanks for the hint, that is a different solution, but I like it. ;-)

Keep up the good work!
Best regards, Martin

------------------------------------------------------------------------
Martin Forisch
Leonard Bernstein Strasse 8/1/2.3
1220 Wien
Mobile: +43 664 1647780
------------------------------------------------------------------------
Das Leben selbst ist es, das dem Menschen Fragen stellt.
Er hat nicht zu fragen, er ist vielmehr der vom Leben her Befragte,
der dem Leben zu antworten - das Leben zu ver-antworten hat.
© Viktor Frankl
------------------------------------------------------------------------
