### ISSUE TITLE
Test Pilot: Compatability (Developer Edition)

### ISSUE THREAD

**Issue by bnb** [Quicksaver/The-Fox--Only-Better#173]
Hello!

I just installed the Test Pilot extensions, and noticed that The Fox is breaking a bit. Specifically, the tab bar is a bit messed up because there's a transparent space where the tabs used to be. Would be nice to have the width of it not go past the tab center. Additionally, it's a bit unresponsive - have to flail around a bit to get it to display.

**Comment by Quicksaver** [comment]
> there's a transparent space where the tabs used to be

I do see some issues with Tab Center when used together with Slim Chrome, but I don't understand this part, I don't have any transparent space anywhere. Can you send me a screenshot of this please?

**Comment by Quicksaver** [comment]
And since we're at it, can you test [beta version 1.4.5b4](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.5b4) and see if it fixes all your issues with Tab Center?

**Comment by Quicksaver** [comment]
Please reopen if you still have any issues.
