### ISSUE TITLE
Feature request: Alt+Number to access search engine dring urlbar popup

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/The-Fox--Only-Better#174]
Move the mouse to click the search engine icon is a large span movement, it would be better if have a numeric accesskey (hidden) for keyboard operation.

Optional implementation:
1. A delay (1000ms) for two-number inputs or automatically zero padding.
2. Show these numbers if hold down the Alt key more than 3000ms.

**Comment by yfdyh000** [comment]
Seems can be solved using keywords [number] for search engines.

Some deficiencies/complaints:
No ways to set two keywords for one, although this may be unnecessary and irrelevant.
Search suggestions still uses the current search engine when using keyword.

**Comment by Quicksaver** [comment]
You can also use Ctr+Up/Down to choose between search engines.

**Comment by yfdyh000** [comment]
In that scenario (editing Wikipedia) I often switch search engines almost every time, and I have more than 10 search engines, although generally only use 4 of them. Ctrl+Up/Down is useless for the frequent switching. Also, I have to input a character and waiting for the popup in order to use the hotkeys, it cannot be used directly when the focus in the address bar.
