### ISSUE TITLE
I propose to create an active area for activation of the panel.

### ISSUE THREAD

**Issue by gegemon2012** [Quicksaver/The-Fox--Only-Better#175]
![beyond australis](https://cloud.githubusercontent.com/assets/15074580/15567810/0f686fe6-2331-11e6-844b-46c9e815b7ec.jpg)
For example I use a supplement Tab scope. Point to Tab I get a preview of tabs but if you make a special area as shown in the screenshot it is possible to activate the panel by pointing the cursor to this area. Of course the area can be made smaller than in the screenshot, and only in one corner, and add the ability to customize its transparency.

**Comment by Quicksaver** [comment]
I do understand there can be some behavior improvements when the add-on is used together with Tab Scope (I use it myself). But adding areas on the webpage itself to show the toolbars is something that I don't agree should be done at all. There are many pages that keep things in the corners (counters, indicators, links, etc). Those areas would cover them and make that inaccessible, meaning you couldn't bring the cursor and click there for instance.

There's just no good way for the add-on to know automatically whether there is something under those areas or not, so it would have to always show/activate those areas in all cases. It could potentially cause more harm than the good it would bring.

But as I said, I do agree that there can be some improvements with Tab Scope, that's already on my to-do list. ;)
