### ISSUE TITLE
Suggest preference setting is not saved, everytime restored on launch firefox (bookmarks,history,open tabs).

### ISSUE THREAD

**Issue by F5lJA7sJ17Af9GdI** [Quicksaver/The-Fox--Only-Better#176]
HI!
I try to fix these thousand times, but still alive. :)

Use Refreshed firefox 46.0.1.
Add the addon Beyond Australis 1.4.5.
Open about:thefoxonlybetter#awesomeBar.
Check Enhance my Awesome Bar,and uncheck History, Bookmarks, and Open tabs.
Open about:preferences#privacy and uncheck location bar settings all. ---(1)
----I want to use Search suggestions only.

Relaunch firefox.
Open about:thefoxonlybetter#awesomeBar.
Look unchecked History, Bookmarks, and Open tabs.
Open about:preferences#privacy and look location bar settings. ---(2)
Compare (1) and (2).

Addon's settings are still, but firefox's settings are changed by something.
I think firefox's settings override addon's settings. 

I find to keep location bar settings.
That is to uncheck "Show search suggestions in location bar results."
Though I cannot use search suggestions.

**Comment by Quicksaver** [comment]
Well, that's uber embarrassing... How could I have not noticed that... Thank you for letting me know, I've already pushed an update with this fixed.
