### ISSUE TITLE
Partial appearence

### ISSUE THREAD

**Issue by DotTheI** [Quicksaver/The-Fox--Only-Better#178]
I guess it started with FF46 that the bar sometimes appears partially and it takes some mouse pointer movements over it to have it revealed fully
![2016-06-03 8 53 10](https://cloud.githubusercontent.com/assets/10737439/15770070/e5da8c3a-2971-11e6-8189-340d7555749c.png)
![2016-06-03 8 53 31](https://cloud.githubusercontent.com/assets/10737439/15770072/e7be9a28-2971-11e6-8e6a-a2f319134785.png)

**Comment by Quicksaver** [comment]
That's very strange. I'll have to see if I can replicate this. Can you get me some sort of steps to get it to not appear completely like that? Or does it seem completely random?

**Comment by DotTheI** [comment]
@Quicksaver I haven't identified any pattern yet, so far it seems to be appearing randomly. I'll be paying more attention to the circumstances when it happens in order to report to you.

**Comment by Quicksaver** [comment]
In particular, please try to notice if it happens on any type of webpage, like flash videos, or pages with java, or anything like that (I assume in your screenshot that's on a new tab?)

**Comment by DotTheI** [comment]
The issue has not been resolved with the latest Firefox updates as I hoped it would. I've been trying to see a pattern, but I did not - it happens randomly. The last time I noticed it was when I opened up this page https://github.com/Quicksaver/The-Fox--Only-Better/issues/178, clicked on 'Sign In'. As the page loaded I moved the cursor to the bar and it did not appear fully until the page finished loading.

**Comment by DotTheI** [comment]
The problem doesn't occur when No Animation is selected

**Comment by Quicksaver** [comment]
First of all, I'm sorry it took me so long to respond.

In all this time I have never experienced anything of the sort. Could I ask you to try disabling all your other add-ons for a little bit (however long it normally takes for this bug to happen) and see if it still happens?

Also, what operating system are you on? Do you have hardware acceleration enabled? Have you tried [disabling it](https://support.mozilla.org/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration)?

**Comment by Quicksaver** [comment]
And please try with [beta version 1.4.7b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.7b1) if you can, to see if it makes any difference for you.

**Comment by DotTheI** [comment]
@Quicksaver Thank you! The latest beta version seems to have fixed the problem :)

**Comment by Quicksaver** [comment]
Well, that's good at least. Please let me know if it starts happening again.
