### ISSUE TITLE
FVD Speed ​​Dial. Overlap groups.

### ISSUE THREAD

**Issue by osminogig** [Quicksaver/The-Fox--Only-Better#179]
Hello ! Your addon one of the best, but..
When you open a new tab, bookmarks bar overlaps groups :(
I would like to switch hide/show Slim Chrome start in a new tab.
Or at least please make an exception chrome://fvd.speeddial/content/fvd_about_blank.html
Thank you !

**Comment by Quicksaver** [comment]
I believe there is an option in Speed DIal to not change focus to the location bar when its page is opened. Doesn't that help with your case?

**Comment by osminogig** [comment]
IMHO focus in adress bar in new tab - only true solution.
Likely users of other Speed Dials would also be unhappy with such behavior a Slim Chrome.
(I have a navigation bar is always displayed, but here are the bookmarks bar closes access to groups)
Well, we'll have to look for another tool to manage bookmarks Panel..
Thanks for your work ! Good luck !

**Comment by Quicksaver** [comment]
So the problem is the bookmarks bar appears over the top area of the speed dial page, but not the navigation (location) bar because that's always visible. So the speed dial option I mentioned is useless. Is this correct?

**Comment by osminogig** [comment]
Yes everything is correct.
But is it not reasonable to add a setting behavior Slim Chrome in a new tab?
In the meantime, you can optionally set the "Hide BookmarksBar"..
(Firefox 47.0)

**Comment by Quicksaver** [comment]
I would say the bookmarks bar shouldn't appear at all in that case. I'll have to check it out and see what's happening exactly.

**Comment by osminogig** [comment]
Hi!
I hung up on gesture of a mouse to hide/show bookmarks bar, but it appears only if to bring the cursor :((
But I want to use and Slim Chrome and to operate bookmarks bar !
It would be great to separately control the hiding the navigation bar and bookmarks bar.

Very sorry also that bookmarks bar on the edges clipped when comes the struggle for each pixel..

**Comment by osminogig** [comment]
And another bug: Twin Sidebar disappears automatically on the page
chrome: //fvd.speeddial/content/fvd_about_blank.html

**Comment by Quicksaver** [comment]
I'm sorry it took me so long to get to this. This should be fixed in [beta version 1.4.7b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.7b1). Please try it out and let me know how it works for you.

As for your other issues, they are completely unrelated to Beyond Australis. If you still have any of them, please open issues in their respective support pages. :wink:
