### ISSUE TITLE
Make mini-bar transparent

### ISSUE THREAD

**Issue by Mesqalito** [Quicksaver/The-Fox--Only-Better#181]
When mini-bar is automatically showed upon tab switching or navigation or entering text it covers part of the page which may usually contain important information. I can't see it until mini-bar disappears. It will be convenient to have this mini-bar semi-transparent so I could see content behind mini-bar without need to wait for it to disappear.
Opacity 70%-75% would be perfect.

**Comment by Quicksaver** [comment]
That would make it not fit into the top toolbars at all, so I don't think I'll be adding this ability directly to the add-on. You can still do it easily through Stylish though, please let me know if you need any help with creating a userstyle to do it, and I'll be sure to help you with it.
