### ISSUE TITLE
Minor bug about back button

### ISSUE THREAD

**Issue by BurningRaptor** [Quicksaver/The-Fox--Only-Better#182]
![bug](https://cloud.githubusercontent.com/assets/10308169/16074879/25687518-331f-11e6-853c-12e75014af9c.png)
The back button is slightly shorter than the url bar.
Meanwhile, the forward button is quite well.
![bug2](https://cloud.githubusercontent.com/assets/10308169/16074937/5777836e-331f-11e6-96bd-69a3c17f121a.png)
Running at Win10, Firefox 46.0, Beyond Australis 1.4.6

**Comment by Quicksaver** [comment]
I'll have to fix that, thanks for letting me know.

**Comment by FlameRaptor** [comment]
BTW, atfer hiding #theFoxOnlyBetter-slimChrome-slimmer, how to hide this line?
![default](https://cloud.githubusercontent.com/assets/10308169/16075315/023f2c2e-3321-11e6-86b9-c0ae1ada4744.png)

**Comment by Quicksaver** [comment]
That's the toolbox's border. I don't remember offhand how to hide it, try removing the bottom border from #navigator-toolbox, or perhaps its box-shadow or an :after element.

**Comment by Quicksaver** [comment]
I'm sorry it took me so long to get to this. This should be fixed in [beta version 1.4.7b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.7b1). Please try it out and let me know how it works for you.

**Comment by BurningRaptor** [comment]
@Quicksaver It does work. Thanks!

**Comment by Quicksaver** [comment]
Great, thanks for letting me know. 😄
