### ISSUE TITLE
Respect Searchengine Keywords

### ISSUE THREAD

**Issue by Thaodan** [Quicksaver/The-Fox--Only-Better#183]
Firefox has the option to set a specific keyboard for each search engine for the searchbar.
It would be nice if these keywords would be usable to select a search engine in the urlbar.

**Comment by Quicksaver** [comment]
It does, doesn't it? What do you mean by "specific keyboard"?

**Comment by Thaodan** [comment]
I meant when you set g as keyboard for google in search engine you enter g <your search> to search with google but nevermind it already does, I just added a @ like I did with omnybar and it didn't worked.

Also it would be nice if would be possible to hide the search engine icons and just search with keywords

**Comment by Quicksaver** [comment]
You can already do that without the add-on. ;)

**Comment by Quicksaver** [comment]
(Didn't mean to post yet.) But if you'd rather keep it, you just have to go to your Firefox's options - Search, and uncheck all your search engines,s o they won't appear.
