### ISSUE TITLE
autocomplete not working as expected

### ISSUE THREAD

**Issue by skirem** [Quicksaver/The-Fox--Only-Better#185]
when I start to type a website I visited before it shows autocompletion and suggestions beyond it, when I hit RETURN it opens the suggestion and not the already completed URL. this is very confusing and I don't see a setting to change this behaviour.

**Comment by Quicksaver** [comment]
I'm not sure I follow. When you hit return/enter, it should take you to the selected entry in the list, the first one by default unless you use the arrow keys to select another one. Is this not happening?

Also, does that only happen with the add-on enabled, or if you disable it does it still happen?

**Comment by skirem** [comment]
hi, thank for your answer. it takes me to the first entry of the suggestion
list, but the autocomplete shows something differnt. and its not the
extension, also without. sorry for stealing your time. wbr erik

2016-07-22 19:21 GMT+02:00 Luís Miguel <notifications@github.com>:

**Comment by Quicksaver** [comment]
If that happens without the add-on, then you should bring it up with Mozilla, although that may be working as expected, even if it seems a bit counter-intuitive.

**Comment by yfdyh000** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1292310
