### ISSUE TITLE
Inconsistent rolling out of the toolbar with Tree Style Tabs add-on

### ISSUE THREAD

**Issue by Musa-Ali** [Quicksaver/The-Fox--Only-Better#186]
I'm using Tree Style Tabs add-on and currently toolbar rolls out on hover only every other time(more or less).  

If I manage to hover over Sky Lights - then it opens no problem. But just moving the cursor on window title panel often fails to open the toolbar - no matter how long I wait. 

Also, may I suggest adding option to open toolbar on window title panel click?

**Comment by Quicksaver** [comment]
If you disable all other add-ons except for Beyond Australis, does that also happen?

Adding a "show on click" function won't really matter, because the toolbars should be shown every time the mouse enters the top area anyway.

**Comment by Musa-Ali** [comment]
Sorry for the long wait. I tested it out with/without addons. Without Tree Style Tabs it works perfectly. But with Tree Style Tabs - it's inconsistent. The faster you move the mouse - the more often it doesn't open. And if lower sensitivity to open (sorry, not sure how it's called in english) - it fails to open at all (unless I'm pixel perfect on that thin Sky Lights panel).

I think it might be related to how TST changes top panel from tabs panel to Window title panel.

**Comment by Quicksaver** [comment]
I'm sorry it took me so long to get to this. I've made several improvements to [beta version 1.4.7b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.7b1) in order to more easily show the toolbars when moving the mouse to the titlebar when using TST. Please try it out and let me know how it works for you.
