### ISSUE TITLE
Slim chrome is not full width

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/The-Fox--Only-Better#195]
A conflict with "Tab Center" extension...

Steps to reproduce:
1. Install TC: https://people.mozilla.org/~bwinton/TabCenter/tab-center.xpi
2. Pin the TC sidebar using the toolbar button provided
3. Resize the TC sidebar to be narrower using the splitter
4. Set the slim chrome to "Full width" and hover the nav bar to reveal it

Notice when TC is pinned (+ the width is not at default), the left edge of the top chrome isn't calculated dynamically. When TC is unpinned, the chrome width looks as expected.

**Comment by Keith94** [comment]
I don't think it's fixed. The toolbar's width seems to be fixed at a small size.. tested latest code from both addons.

![firefox_2016-11-15_05-39-18](https://cloud.githubusercontent.com/assets/5490615/20307821/19f4e3fc-aaf6-11e6-8024-17ecec108849.png)

**Comment by Quicksaver** [comment]
Quite... how very peculiar...

**Comment by Quicksaver** [comment]
How about now? :)

**Comment by Keith94** [comment]
Yes, that looks proper. Maybe slim chrome should also take into account when another sidebar is open at the same time (e.g. bookmarks sidebar)? Currently it overlaps the sidebar.

![firefox_2016-11-15_08-32-36](https://cloud.githubusercontent.com/assets/5490615/20314177/26462d74-ab0e-11e6-946e-c51b42168745.png)

**Comment by Keith94** [comment]
I believe the slim chrome could use tweaking for **Tree Style Tab** as well. Currently there is a small gap between Tabs toolbar and slim chrome (you might need the splitter disabled):

![firefox_2016-11-15_08-40-57](https://cloud.githubusercontent.com/assets/5490615/20314695/e6c867d2-ab0f-11e6-8c7f-4205b50f9d3c.png)

And when a sidebar is open, the width stays the same:

![firefox_2016-11-15_08-45-04](https://cloud.githubusercontent.com/assets/5490615/20314682/ddb419ac-ab0f-11e6-9b74-685d100dad26.png)

In my opinion I would like to see the slim chrome expand the full width of the browser when using Tree Style Tab, since the tabs are positioned below the top toolbars anyway. Maybe an about:config preference could work for that?

**Comment by Quicksaver** [comment]
> Yes, that looks proper. Maybe slim chrome should also take into account when another sidebar is open at the same time (e.g. bookmarks sidebar)? Currently it overlaps the sidebar.

Actually that's only happening in that case because of Tab Center, without that the toolbars appear over the sidebar as they should by default.

There is a preference in about:config to not cover the sidebars though: ```extensions.thefoxonlybetter.slimOnlyOverContent```, I'll see if I can automate that in this case though, as of course it looks just silly like that.

**Comment by Quicksaver** [comment]
There we go. It should only show the toolbars over the webpage when using both Tab Center and Tree Style Tab. And with TST it should reach the edge/resizer/grippy much better.

By the way, please try to open different issues for things like those. I guess they are "kinda related" to the original post, but not really by that much. 😉

**Comment by Keith94** [comment]
Okay, thanks for the fixes. :) I'll open a follow-up issue.
