### ISSUE TITLE
Slim Chrome breaks the interface after disabling Tab Center

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/The-Fox--Only-Better#196]
While Beyond Australis is active, something appears to break after disabling the Tab Center extension.

1. Start by installing Beyond Australis + Tab Center: https://people.mozilla.org/~bwinton/TabCenter/tab-center.xpi
2. Then go into Add-ons Manager and disable TC. Notice that the tabs are not restored to their horizontal layout, and the vertical tabs space becomes blank.
3. As an extra step, if you disable Beyond Australis, the top toolbars also disappear and are not restored until a restart.

**Comment by Quicksaver** [comment]
Yep, unfortunately I don't believe there's much I can do on my end. I've opened https://github.com/bwinton/TabCenter/issues/783 for this.
