### ISSUE TITLE
Resizing Tab Center sidebar is slow to update

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/The-Fox--Only-Better#197]
The performance of resizing the Tab Center sidebar appears to be impacted negatively when Beyond Australis (and possibly your other bootstrapped addons) are enabled.

Just install Tab Center (https://people.mozilla.org/~bwinton/TabCenter/tab-center.xpi) and pin the sidebar open, then do some comparisons resizing it with Beyond Australis enabled and disabled. I made some quick comparisons below if needed.

The normal behavior (without Beyond Australis):

![ezgif-482875139](https://cloud.githubusercontent.com/assets/5490615/18428162/44948e98-7881-11e6-8643-d3ebfe1565ef.gif)

The slow/laggy behavior (with Beyond Australis):

![ezgif-1547963810](https://cloud.githubusercontent.com/assets/5490615/18428233/a391e85a-7881-11e6-8f00-65957a85e2b4.gif)

**Comment by Quicksaver** [comment]
Can you please try the latest code from master here and also the latest from master at Tab Center? I don't really see any difference on resizing with or without Beyond Australis, although I do see a lot of jarring overall (https://github.com/bwinton/TabCenter/issues/784).

**Comment by Keith94** [comment]
Hmm you're right, the differences I saw before have gone away for some reason. I'll reopen if I see anything else.
