### ISSUE TITLE
Right-clicking bookmarks button opens context menu at wrong location

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/The-Fox--Only-Better#199]
Basically when the mini bar is active, the bookmarks button is displayed next to the urlbar, and if you right-click the bookmarks button, the context menu opens at the top left corner of the screen.

Also the star icon looks somewhat blurry or compressed in the mini bar, while also lacking a border around it too (when hovered).

**Comment by Quicksaver** [comment]
That should prevent the minibar from expanding immediately when clicked, so the menu should open in the correct place now. But the star icon looks fine to me, can you post a screenshot of this please? It has the proper borders/effects when hovered as well for me. Does that happen without any other add-ons enabled?

**Comment by Keith94** [comment]
Alright, the menu issue is fixed. And for the bookmark icon, here's some screenshots on Windows 8. Also no other add-ons are installed.

Normal toolbar (proper):
![firefox_2016-11-16_08-43-42](https://cloud.githubusercontent.com/assets/5490615/20356370/2c0b59fc-abd9-11e6-931e-f983d418ee12.png)

Mini bar:
![firefox_2016-11-16_08-44-05](https://cloud.githubusercontent.com/assets/5490615/20356372/2d803cb2-abd9-11e6-878e-c0a1d189a39d.png)

**Comment by Quicksaver** [comment]
That should fix those issues, along with a few others I found. Please do try it and let me know if it's still not right for you, or of course if I screwed something else up in the process. 😉
