### ISSUE TITLE
Show top toolbars when hovering title bar

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/The-Fox--Only-Better#200]
When using an extension like Tab Center, which has the title bar visible at all times at the top, it would be more convenient if we can throw the mouse to the top of the screen, and still have the navbar/bookmarks bar become visible, without having to position the cursor very carefully each time like we currently have to.

**Comment by Quicksaver** [comment]
Already fixed for #186, I'll post a beta there soon, so please follow that thread if you'd like to try it out when I do. :)

**Comment by Keith94** [comment]
Thanks, I installed latest version from master and it works good so far.

**Comment by Quicksaver** [comment]
That's great! Thanks for letting me know. :)
