### ISSUE TITLE
TFOB doesn't load when firefox (FF52.0a1) takes too long to start

### ISSUE THREAD

**Issue by SquirrelPerson** [Quicksaver/The-Fox--Only-Better#202]
Since a day or two, the navigation bar won't auto-hide when I start Firefox (nightly), nor will the skylight appear. The moment I open about:thefoxonlybetter though, it suddenly works again.

Opening a new window enables the addon too, but only in that new window.

edit: I have done some more testing. It also happens on a different pc with similar addons, but it does not happen on a new profile with just TFOB. My guess is that a different addon might be causing this, I'll try to narrow it down.

Edit 2: I copied my profile so I could remove addons one by one, to find the culprit. When I closed all but one of 38 tabs, the problem mysteriously went away. I will now check if a specific website or number of websites caused this issue.

edit 3: So it happens on my old profile when firefox starts with more than 1 tab open, but this is not true for a new profile with just TFOB. If I start my old profile with just one tab open, TFOB works as expected.

edit 4: As I remove more and more addons, it allows for more tabs to be loaded at start without TFOB failing to load, and I've gotten to the point where I can't get it to fail anymore. **I suspect that it fails to load when Firefox and other addons take a long time to start.**
I will now try to slow down a new profile with addons to try and reproduce the issue.

---
## Results of my testing

I can reproduce the issue on 2 different machines following these steps:

1- starting from a fresh profile, install these addons: 
- Adblock Plus
- Beyond Australis (obviously)
- Mouse Gesture Suite
- NativeShot
- Profilist 
- Pushbullet
- Reddit Enhancement Suite
- videoresumer

2- set the startup preference to  "show my windows and tabs from last time"
3- open a few tabs with sites like google, imgur.com, cnn.com and yahoo.com
4- restart firefox

**Comment by SquirrelPerson** [comment]
While the problem still exists, I have since figured out that pressing F9 twice to toggle slim chrome also causes the addon to successfully load. This workaround is obviously less bothersome, but still a workaround.

**Comment by SquirrelPerson** [comment]
And now it seems to have disappeared. Everything seems to work on startup again.

**Comment by Quicksaver** [comment]
The next update will have a few fixes to prevent failures on initialization. Of course I can't be sure they are the same as the ones you experienced, but if you ever see anything like this again please let me know.
