### ISSUE TITLE
Display the progress of loading pages in the location field

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/The-Fox--Only-Better#206]
Something similar to the green bar that fills from left to right, when performing a search in Windows Explorer.
It would also be a very convenient feature in Beyond Australis' location mini bar, making the mini-bar stay present until the page finishes loading.

**Comment by Quicksaver** [comment]
You can use [Status-4-Evar](https://addons.mozilla.org/firefox/addon/status-4-evar/) for that, it should work perfectly fine with Beyond Australis, so there's no need to add extra features to the add-on, unless you can't use that one for some reason.
