### ISSUE TITLE
display the location of hovered links in the location bar

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/The-Fox--Only-Better#207]
Replace the standard floating tooltip with the titular setup option.  It is preferable to have all URL related info in one place, for consistency.  This would be great if displayed in the location mini bar which pops up occasionally.  Stylized text (color/bold/etc.) could be used to differentiate it from the current page's address {maybe use Firefox's existing link color setting by default}.

**Comment by Quicksaver** [comment]
Also in [Status-4-Evar](https://addons.mozilla.org/firefox/addon/status-4-evar/).

**Comment by jmain33** [comment]
Status-4-Evar isn't capable of making the 'mini location bar' show up.  It targets the standard location bar as the area to which Firefox's relevant info is relocated; so it's displaying things that I can't actually see when using Beyond Australis.

I thought these suggestions (#206 & #207) would be in line with the overall scope of Beyond Australis and what it aspires to do {based on the description provided at AMO; there can be more than one option tackle a solution BTW, though if you don't agree that these features belong in BA I would be understanding}.

Status-4-Evar works nicely on its own; but when combined with some of your add-ons it reveals some quirky, or generally incompatible, behavior (as we've discussed previously in the Puzzle Bars repository).  Even though #206 mostly works well with Beyond Australis, the mini location bar does go away sometimes (very rarely) while the page loading progress is displaying.

**Comment by Quicksaver** [comment]
> Status-4-Evar isn't capable of making the 'mini location bar' show up

It does, or it should at least. ;) The mini bar is the exact same element as the location bar, it's just styled a little differently. Doesn't it appear for you? If not, that's a bug, as I remember I specifically added compatibility for it some time ago.

> I thought these suggestions (#206 & #207) would be in line with the overall scope of Beyond Australis and what it aspires to do

They absolutely do, that's not what I meant though. If another add-on can already do something, and it works correctly with this one, I believe there's no point in adding redundant functionality. So I would rather focus on other things. After all I can only do so much, so I need to prioritize. :)

> Even though #206 mostly works well with Beyond Australis, the mini location bar does go away sometimes (very rarely) while the page loading progress is displaying.

That's a bug. Can you please open an issue specifically about it so I don't forget to check it out? It worked perfectly fine the last time I tried it, but I admit I haven't tried S4E in a while, so some change may have caused it to go away every once in a while.

**Comment by jmain33** [comment]
All this is very understandable Luís, thanks for clarifying.
> It does, or it should at least. ;) The mini bar is the exact same element as the location bar, it's just styled a little differently. Doesn't it appear for you? If not, that's a bug, as I remember I specifically added compatibility for it some time ago.

I set S4E to show links in the location bar on hover, but it indeed does not call upon the mini location bar.  While I'm sure the text is being displayed in the location bar itself (which isn't visible) the mini bar isn't brought up.

I will open an issue for this and the progress indication, as they are the same issue I suppose.
