### ISSUE TITLE
Mini Location Bar Unresponsive to Status-4-Evar Settings

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/The-Fox--Only-Better#210]
The mini bar doesn't seem to have awareness of Status-4-Evar's ability to display hovered links, loading progress, page status, etc…

The display of loading progress works OK on the surface, but this is only due to both add-ons being set to display page load progress in the location bar.  I don't believe there is any actual communication happening between the two add-ons in this regard (i.e. Beyond Australis' mini location bar does not explicitly recognize that Status-4-Evar is also displaying the loading progress).  So if Beyond Australis' "view mini bar while pages are loading" setting `fails/or is turned off` it does not fall back to the fact that S4E is displaying progress there.

**Comment by Quicksaver** [comment]
It works for the loading indicator for me. For instance if I refresh the page, it shows the mini bar showing the current progress (the minibar normally doesn't appear at all when simply refreshing the page).

Although it's true about the hover links and status at least.

**Comment by jmain33** [comment]
Thanks for your effort, I'll see how it goes when the update arrives.

**Comment by Quicksaver** [comment]
[Beta version 1.4.7b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.7b1) should show the mini bar when moving the mouse over links (if S4E is set to show the links in the location bar of course). I also made some tweaks so that the mini bar shouldn't hide before the page loading progress indicator is gone (i.e. until it's finished loading).

Please try it out and let me know how it works for you.

**Comment by jmain33** [comment]
Links are showing :relieved:, but the mini-bar is using as little horizontal space as possible.  There is an alignment setting in S4E that changes the position of the text (LEFT¦RIGHT¦FIXED); plus a slider for the right and fixed positions that I suppose simply shifts the text's position.  The 2 screenshots below show the output for the same hovered link with an alignment of 100 (Current Location) & of 10 (near the Status Text end).  

_------here in the "current location" position------------here in the"status text" position-------_
![2016-11-17_180207](https://cloud.githubusercontent.com/assets/364460/20412386/531ae38e-acf4-11e6-97be-3cd8158f839b.png)   ![2016-11-17_180613](https://cloud.githubusercontent.com/assets/364460/20412391/5d2b19b6-acf4-11e6-891c-d67347bf44b0.png)

The mini-bar is showing much less "links" text than I'd expect and there don't seem to be any settings in S4E which alter the (minimum)length of the text.

My guess would be that Beyond Australis needs to maximize the length of the mini-bar to the length of the text being displayed.  Let me know if I should expect a fix on your end or head on over to the S4E dev.

_This will also have an effect on the way loading status text is shown in the mini-bar, when a link is hovered while the loading info is in the bar it will shrink to the size in the screenshots above; and remain that size for an extended period, though it eventually snaps back to the typical length if loading progress takes long enough._

**Comment by Quicksaver** [comment]
It also has a tiny one-pixel transparency at the bottom, which I hate, I can never figure out why that happens...

I'll look into all this. It definitely should extend to the length of the hovered link at least. But it should not extend over half the width of the window. I can't tell from the screenshots, that's not half of the window right?

**Comment by jmain33** [comment]
> It also has a tiny one-pixel transparency at the bottom, which I hate, I can never figure out why that happens... :smile: 

 
> I can't tell from the screenshots, that's not half of the window right?

Those are confusing, guess I shouldn't have cropped it.  The window width is 1080px those caps are only 295px wide.

**Comment by Quicksaver** [comment]
Alright, the width issue should be fixed in [beta version 1.4.7b2](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.7b2). Could you try it out and let me know how it works for you, especially if the tiny background offset that I mentioned is also still happening?

**Comment by jmain33** [comment]
Looks Good, I can see the full link now.

**Comment by Quicksaver** [comment]
> It also has a tiny one-pixel transparency at the bottom

What about this, is it still there?

**Comment by jmain33** [comment]
Haha 😄, Sure whatever!

It was gone in b2 now it's back in b3

**Comment by Quicksaver** [comment]
> It was gone in b2 now it's back in b3

And the weirdness continues... Do you have [Stylish](https://addons.mozilla.org/firefox/addon/stylish/)? Can you tell if applying this style helps:
```CSS
#theFoxOnlyBetter-slimChrome-container[onlyURLBar]:not([hover]) #nav-bar #urlbar-container {
	padding: 2px 0;
}
```

**Comment by jmain33** [comment]
I don't use that particular extension.  I will install it, try that slice of code and let you know how it goes.

**Comment by Quicksaver** [comment]
There's no need in that case, I made a quick build with that patch. Try [beta version 1.4.7b4](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.7b4),

**Comment by jmain33** [comment]
Looks entirely good now.  beta4 fixed it.

**Comment by Quicksaver** [comment]
Awesome! I guess I can finally close this then. :)
