### ISSUE TITLE
Minor flaw with the bottom border

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/The-Fox--Only-Better#211]
When the overall height of the toolbar reaches a certain point there is a slight misalignment in the bottom edge of the toolbar (the horizontal edge is protruding by a pixel). 

This occurs when there is more than one toolbar attached to the navigation bar (i.e. the additional toolbars from CTR) or if a toolbar is taller than the norm (such as the bookmarks toolbar).

**Comment by Quicksaver** [comment]
Can you post a screenshot of this please? And does it also happen without CTR? (you can use the bookmarks toolbar for example to test)

**Comment by jmain33** [comment]
This is truly a <ins>MINOR</ins> flaw Luís, the bottom edge is simply extending by one pixel from having a smooth transition with the Australis theme.  I already tested with only the 'bookmarks toolbar' before starting this topic :wink:; what I did forget to mention is that it only presents itself with the Australis style, so this could be a Firefox contingency.

Here's a couple of screenshots so you can see if it's even worth caring about!
![2016-11-16_163248](https://cloud.githubusercontent.com/assets/364460/20366798/acf5b0a8-ac1a-11e6-8e12-d1d8c16bae6b.png) ![2016-11-16_163646](https://cloud.githubusercontent.com/assets/364460/20366863/fd20c7de-ac1a-11e6-8c3e-66c4ec44893b.png)
_The first one is the "wider" bookmarks toolbar, the second is with the "standard width" top puzzle bar._

**Comment by Quicksaver** [comment]
Ah right, yes it will look like that in certain cases. It's a limitation of the way the side curved borders are drawn (the problem is not actually the bottom border being lower, but the side border not matching it pixel-perfectly.

See #95 for more details if you want. :wink:
