### ISSUE TITLE
Display slim chrome over sidebars with Tree Style Tab

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/The-Fox--Only-Better#212]
In #195 you added some compatibility fixes for TST and TC to only show slim chrome over the webpage by default.

It looks proper in most cases, but I would like to optionally display slim chrome over all sidebars too including TST (the current add-on I use). The `slimOnlyOverContent` pref doesn't make a difference in this case :(

**Comment by Quicksaver** [comment]
Right, I had meant to do that but forgot and left it to only consider the content space, sorry about that.

**Comment by Keith94** [comment]
No worries, thanks for understanding.

**Comment by Quicksaver** [comment]
Alright, with that it should obey the ```slimOnlyOverContent``` preference when using TST. Note that with Tab Center it's unchanged, it always behaves as if that preference is true because TC shifts things to show the navigation bar next to the tabs, so it doesn't make sense otherwise.
