### ISSUE TITLE
Border outline issue with popout windows

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/The-Fox--Only-Better#213]
STR:

1. Enable slim chrome but have the nav bar visible
2. Enable bookmarks toolbar
3. Open a popout window from somewhere... for example [YouTube Plus](https://addons.mozilla.org/firefox/addon/youtube-plus) adds a popout button underneath a YouTube video
4. Hover over the nav bar, there should be a border/outline where the bookmarks toolbar should be, but it's empty inside

**Comment by Quicksaver** [comment]
That should fix that.
