### ISSUE TITLE
[Feature Request] Restore Tab URL When Awesome Bar Left Empty

### ISSUE THREAD

**Issue by EMLVIRUS** [Quicksaver/The-Fox--Only-Better#215]
If current tab URL is deleted for searching in awesome bar but later nothing is typed in (no search submitted), URL in awesome should be restored instead of leaving the whole place empty.

**Comment by Quicksaver** [comment]
I believe an empty value is still a valid user-input value and should be treated as such (even if it's a useless one). That's how the location bar has always worked, and I don't believe it's within the add-on to change that. Hit <kbd>Esc</kbd> and it'll be reset back to the current location.

**Comment by Quicksaver** [comment]
I believe an empty value is still a valid user-input value and should be treated as such (even if it's a useless one). That's how the location bar has always worked, and I don't believe it's within the add-on to change that. Hit <kbd>Esc</kbd> while the cursor is in the location bar and it'll be reset back to the current location.
