### ISSUE TITLE
The bar is not hidden on firefox nightly

### ISSUE THREAD

**Issue by Mte90** [Quicksaver/The-Fox--Only-Better#216]
I switched from firefox beta to firefox nightly and the bar is not hidden anymore.
The extension works (hide etc) only when i open the preferences of the extension itself.

**Comment by Quicksaver** [comment]
Does [beta version 1.4.7b1](https://github.com/Quicksaver/The-Fox--Only-Better/releases/tag/v1.4.7b1) work properly?

**Comment by Mte90** [comment]
Yes fix the problem :-D
