### ISSUE TITLE
Preview Personas in Discovery Panel

### ISSUE THREAD

**Issue by EMLVIRUS** [Quicksaver/The-Fox--Only-Better#220]
See the gif I recorded.
![123](https://cloud.githubusercontent.com/assets/16912240/21092113/7ea00c9c-c085-11e6-8cc3-be89ae77a057.gif)

**Comment by Quicksaver** [comment]
Good catch, thanks for letting me know. I'll see if there's anything I can do.

**Comment by Quicksaver** [comment]
This is an OmniSidebar bug, not a Beyond Australis one.
