### ISSUE TITLE
Beyond Australis configuration

### ISSUE THREAD

**Issue by NeoSeeU** [Quicksaver/The-Fox--Only-Better#221]
I like this fast responding bar pulldown fast, because I sometimes need to repeat editing my uMatrix cookie response while browsing. Do you have faster response? My fader is at the fast end. ->
http://prntscr.com/dphvn7

Q: How is the Colorscheme affecting the bar?
http://prntscr.com/dpiukm

Just for notice and further advancement, it's not an issue.
 Keep up your phenomenal ideas ... Java Hero :)

**Comment by Quicksaver** [comment]
> Do you have faster response? My fader is at the fast end.

That already is almost immediate (75ms delay to be accurate). Unfortunately that minimum delay is required for some things to work properly at the moment, so there's no way to lower it any further right now. But to be honest, between that and 0, I believe the difference would be negligible no matter what actions you want to do.

However, you can select "no animation" and the bar will appear much faster (note that the slider you mentioned above is not the speed of the animation, it's the delay with which it will happen; meaning even if you could set that slider to a lower value, the animation would be unaffected and would still take the same time to appear, so it wouldn't really be a full solution to your problem anyway).

> How is the Colorscheme affecting the bar?

For the dropdown results when typing in the location bar. See the last screenshot at [the add-on's homepage](https://addons.mozilla.org/firefox/addon/the-fox-only-better/).

**Comment by NeoSeeU** [comment]
I understand it's the response delay this fader defines. I tried "no anim " too, Still the bar doesn't come out by my brief mouse hover over. I understand as well some code has to execute, I'm just asking for a bit more smooth response, I can notice down to 35 ms as immediate. As mentioned in OT accessing the uMatrix button quick is vital or else investigation of cookies on cross-link sites would take longer, need it for new sites I visit. How about right click to switch between hidden and steady bar?

Thanks, didn't see all screenshots from addon-site. Do you plan for more stylish bar settings?
