### ISSUE TITLE
Slim chrome partially overlaps the Tab Center sidebar

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/The-Fox--Only-Better#224]
STR:
1. Install Tab Center: https://people.mozilla.org/~bwinton/TabCenter/tab-center.xpi
2. Shrink/unpin the tab sidebar
3. Hover the nav bar to reveal the slim chrome
4. Press Ctrl+Shift+L to reveal tab sidebar

Expected results: Display slim chrome behind tabs (?)

Actual results: The two elements overlap which covers up the search bar
![firefox_2017-01-18_05-57-32](https://cloud.githubusercontent.com/assets/5490615/22066811/87db98be-dd43-11e6-80ad-d4854129e385.png)

**Comment by EMLVIRUS** [comment]
Simply consider the case in your screenshot: if slim chrome is displays behind Tab Center tabs, how can you reach several bookmark folders at the very head?
So I suggest to leave this to Tab Center: another option to prevent Tab Center to auto fit height as slim chrome activated.
