### ISSUE TITLE
Feedly notifier icon disappears with T-F-O-B

### ISSUE THREAD

**Issue by sjossie** [Quicksaver/The-Fox--Only-Better#65]
Love the addon and it was working fine until a few days ago. Now the Feedly notifier icon disappears every time I enable TFOB. Any chance of fixing this bug so that I am able to use your addon again. Thanks.

**Comment by Quicksaver** [comment]
So Firefox 36 is out, and Feedly Notifier's developer just uploaded the next version which should fix this issue. It should be approved soon, so it should update automatically in the next few days, but you can find it already [here](https://addons.mozilla.org/firefox/addon/feedly-notifier/versions/?page=1#version-2.10.0) if you'd like to try it now.

**Comment by sjossie** [comment]
Thanks Luis,

just loaded it and is working perfectly now. Well done.

Stephen

**Comment by Quicksaver** [comment]
Don't thank me, thank Feedly Notifier's developer. ;)
