### ISSUE TITLE
Toolbars failing to disappear completely

### ISSUE THREAD

**Issue by Woowoo678** [Quicksaver/The-Fox--Only-Better#9]
When mousing away, the toolbars will occasionally cease the closing animation abruptly, frozen in a semitransparent, shrunken state. Mousing on and off of the top bar once more will usually clear them away. This issue most frequently occurs when the browser is suffering significant lagging.

**Comment by orschiro** [comment]
Can confirm the issue with version `1.1.8` and Firefox `34.0.5` and will try to find out which add-on might be interfering. Using some custom stiles with `User Style Manager`.

![screenshot](https://cloud.githubusercontent.com/assets/170947/5610669/828488ee-94bb-11e4-8b7f-c4a68c568adb.png)

**Comment by Quicksaver** [comment]
It may not be User Style Manager (USM) itself, but maybe one of the styles you have enabled. If you disable all its styles, but keep USM enabled, does the issue happen?

**Comment by orschiro** [comment]
> It may not be User Style Manager (USM) itself, but maybe one of the 
styles you have enabled. If you disable all its styles, but keep USM 
enabled, does the issue happen?

Yes it does. Makes it more difficult to find the incompatibility.

On 10.01.2015 12:37, Luís Miguel wrote:
>
> It may not be User Style Manager (USM) itself, but maybe one of the 
> styles you have enabled. If you disable all its styles, but keep USM 
> enabled, does the issue happen?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Quicksaver/The-Fox--Only-Better/issues/9#issuecomment-69452870>.
>

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#opensource #degrowth / Love
#bouldering

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by orschiro** [comment]
Correction: it was related to one of my stylesheet which assigned favicons
to bookmarklets.

**Comment by Quicksaver** [comment]
Could you link me to that stylesheet? Or maybe post it here please? I'd like to give it a try and see if I can also reproduce the issue.

**Comment by orschiro** [comment]
Sure. Thanks for looking into it:

|@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
/* Welcome to the Style Editor window of User Style Manager. */

/* Add favicons to bookmarkets
http://forums.mozillazine.org/viewtopic.php?f=7&t=1755885
*/

toolbarbutton[class="bookmark-item"][label="Bitlink"] {
list-style-image: url("https://d1ayxb9ooonjts.cloudfront.net/22f1d0b2154c2f58baf06f92038d262a.png") !important;
}

toolbarbutton[class="bookmark-item"][label="Add event"] {
list-style-image: url("https://calendar.google.com/googlecalendar/images/favicon_v2014_4.ico") !important;
}

toolbarbutton[class="bookmark-item"][label="UU Proxy"] {
list-style-image: url("http://www.google.com/s2/favicons?domain=www.uu.nl") !important;
}

toolbarbutton[class="bookmark-item"][label="jetzt"] {
list-style-image: url("https://github.com/ds300/jetzt/raw/master/img/screenshot.png") !important;
}

toolbarbutton[class="bookmark-item"][label="Squirt"] {
list-style-image: url("http://www.squirt.io/images/logo.png") !important;
}

toolbarbutton[class="bookmark-item"][label="Word Count"] {
list-style-image: url("https://addons.cdn.mozilla.net/user-media/addon_icons/4/4718-64.png?modified=1281079852") !important;
}

toolbarbutton[class="bookmark-item"][label="Save to Zotero"] {
list-style-image: url("http://www.google.com/s2/favicons?domain=www.zotero.org") !important;
}

toolbarbutton[class="bookmark-item"][label="Save to blogtrottr"] {
list-style-image: url("http://www.google.com/s2/favicons?domain=www.blogtrottr.com") !important;
}

toolbarbutton[class="bookmark-item"][label="Save to Mendeley"] {
list-style-image: url("http://www.mendeley.com/favicon.ico") !important;
}
|

On 01/24/2015 02:51 PM, Luís Miguel wrote:

> Could you link me to that stylesheet? Or maybe post it here please? 
> I'd like to give it a try and see if I can also reproduce the issue.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Quicksaver/The-Fox--Only-Better/issues/9#issuecomment-71317512>.
>
​

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#opensource #degrowth / Love
#bouldering

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by Quicksaver** [comment]
So I've been using that style with User Style Manager for a little while, and surfing around the web and moving the mouse over and out of the toolbars like crazy. So far, nothing...

I've decided to report this to mozilla [bug 1125606](https://bugzilla.mozilla.org/show_bug.cgi?id=1125606) since I am just about out of ideas, and I realize this is a big nuisance for you guys... Let's see if they're able to shed any light in the matter. In the meantime, if anyone thinks of anything else that might be relevant to the issue, please post here or on that bug.

I'm very sorry I'm not able to give you all a more prompt solution.

**Comment by Quicksaver** [comment]
BTW, I don't see anything in that userstyle that could even come close to interfering with the toolbars opacity, it's just icons after all... If there is something related to it, it's a bug buried deep in firefox's rendering engine.

**Comment by orschiro** [comment]
I keep experimenting and now it seems to work for some reasons. However, I encounter another issue with the add-on not nicely integrating into my setup:

![image](https://cloud.githubusercontent.com/assets/170947/5899523/8f4880e2-a55c-11e4-9d51-b739c06142ba.png)

Please note the white bar and the half-shown skylights icon.

The custom style I am using is the following:
```
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

toolbar {
    background: #DEDEDE !important;
}

#TabsToolbar:not([collapsed="true"]) + #nav-bar {
   border-top: none !important;
}
```

Could you give me some final advice on how to make the add-on integrate more nicely?

Thanks!

Robert

**Comment by Quicksaver** [comment]
@orschiro try giving a once over to issue #24, it has instructions for how to apply themes to the add-on. In your case, I suggest not styling the toolbars individually like that, but apply any styling you need like suggested in that issue. Please let me know (in that thread) if you need any more specifics and I'll be happy to help. :)

**Comment by Quicksaver** [comment]
Just as an update, has any of you experienced this issue in the most recent versions of firefox?

**Comment by orschiro** [comment]
@Quicksaver 

I cannot report back anymore since I switched from Firefox to Chromium. Sorry!

**Comment by Aralun** [comment]
Could not reproduce on Firefox 40.0a2 (Dev Edition). This reminded me to put it back on! Having space feels good.
