### ISSUE TITLE
Bug/conflict with the Classic theme restorer add-on

### ISSUE THREAD

**Issue by irluck** [Quicksaver/The-Fox--Only-Better#90]
Hi Luis, this happens when on CTR I set the back and forth buttons to be mobile (separated from the nav-bar). Somehow it conflicts with the mini bar in ~~FOV~~ FOB and it gets messed, showing the buttons.

![ctr vs fob](https://cloud.githubusercontent.com/assets/10477345/5692191/c43dedc8-98eb-11e4-90fe-5f722a08876d.png)

I'm not sure if I should try to contact with CTR dev too.

**Comment by Quicksaver** [comment]
There's probably no need for that, I'll check it out and let you know.

**Comment by Quicksaver** [comment]
This will be fixed in the next update, hopefully it will be out in the next week or two. Please let me know if after it updates you still have issues.
