### ISSUE TITLE
Not wide enough with hidden tree-style tabs

### ISSUE THREAD

**Issue by pank** [Quicksaver/The-Fox--Only-Better#91]
Hi

I use this The Fox--Only Better (TFOB) with Tree-Style Tabs (TST).  Since the resolution of my laptop is small I use auto-hide with TST.  When I use the full-width version of TFOB, it does not stretch all the way to the right, even when TSF is hidden which means it's hard to predict where the Firefox menu button is.  I don't know if this is a fundamental limitation of if the problem can be fixed.

*Screenshot of TFOB when TST is hidden.  Width is incorrect*
![screenshot from 2015-02-17 16 52 46](https://cloud.githubusercontent.com/assets/666845/6231197/7194a4a2-b6c5-11e4-8116-cc537386e4f1.png)

*Screenshot of TFOB when TST is displayed: width is correct.*
![with tst open](https://cloud.githubusercontent.com/assets/666845/6231181/4f8ed9a4-b6c5-11e4-93ad-03609591ed51.png)

---Rasmus

**Comment by Quicksaver** [comment]
Even though your first screenshot doesn't actually show it, I do see the problem. I'll try to fix it for the next version. Thanks for letting me know about it.

**Comment by pank** [comment]
On February 21, 2015 12:18:07 PM CET, "Luís Miguel" <notifications@github.com> wrote:
>Even though your first screenshot doesn't actually show it, I do see
>the problem. I'll try to fix it for the next version. Thanks for
>letting me know about it.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Quicksaver/The-Fox--Only-Better/issues/91#issuecomment-75367413

Oh sorry.  You are right. Screenshot are hard. Screenshots that depends on the mouse even more so.

Thanks a lot!
