### ISSUE TITLE
Conflict with Classic Theme Restorer

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/The-Fox--Only-Better#92]
Set the style in TFOB to Australis and check the first box in CTR options as in my screenshot below.  This results in some missing color on the left and right location bar and bookmarks bar as seen in the second screenshot.  All the other styles look fine.

 
![ctr](https://cloud.githubusercontent.com/assets/410799/6490822/1ad8cf72-c277-11e4-9186-5fb0c30eb58a.jpg)

![australis](https://cloud.githubusercontent.com/assets/410799/6490827/1ee49aa6-c277-11e4-9fb1-f6c7f2fe58cc.jpg)

**Comment by Quicksaver** [comment]
Thanks. Already suggested to Aris (CTR's developer) a fix for this as it is much more easily fixed there. Hopefully it'll be in the next CTR beta.
