### ISSUE TITLE
Conflict with FireGestures

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/The-Fox--Only-Better#93]
FireGestures has a mapping called "[Open] Popup menu" which is the PanelUI menu.  I have it set in FG as a Rocker Gesture initiated by the option "left-click with holding right- button:" 

Under TFOB the menu will briefly appear where my pointer is (this is normal) but then immediately move to the upper left hand side of my screen. I suspect setting up a mouse gesture would also produce the same results although I haven't tried this.  If I use the hot dog icon placed on the navigation bar the menu displays below the hot dogs where it should.

Please note that when I bring up the menu via the rocker gesture the hidden toolbars will reappear which at that time the menu moves to the upper left of my screen.

**Comment by Quicksaver** [comment]
Just uploaded beta version 1.1.12b1 to https://addons.mozilla.org/firefox/addon/the-fox-only-better/versions/ which should fix this issue. Care to give it a try? :)

**Comment by Quicksaver** [comment]
Also it's funny you call it the hot dog button, never looked at it that way, I see it as more of a hamburger. :)

**Comment by streetwolf** [comment]
PanelUI works fine via FG.  Thanks Luis.  

 

As far as not seeing the basic Fx toolbars at start up would something like this work?  Take the bookmarks toolbar for example.  There is an option to disable it.  Couldn’t I have it disabled and then at startup of Fx you enable it and then display the TFOB bookmarks toolbar?  Don’t know if this would still show the basic toolbar.  Same for the navigation toolbar.
