### ISSUE TITLE
conflict with this userstyle

### ISSUE THREAD

**Issue by FlameRaptor** [Quicksaver/The-Fox--Only-Better#96]
https://userstyles.org/styles/100548/firefox-small-icons

**Comment by Quicksaver** [comment]
Please try to contact the developer of the userstyle first and see if he can add compatibility for the add-on in it, as it's much easier to do it on the style's side than on the add-on. You can direct him to #24 as it might be useful.

Or you could always just use the add-on's own compact style, which is actually very similar. You also have other options, such as [Classic Theme Restorer](https://addons.mozilla.org/firefox/addon/classicthemerestorer/) which also has a similar feature.
