### ISSUE TITLE
Toolbar edge on OS X

### ISSUE THREAD

**Issue by DotTheI** [Quicksaver/The-Fox--Only-Better#97]
On OS X the upper tool bar edge with TFOB enabled is not as sharp as it should be.
TFOB enabled:
![2015-04-01 22 56 55](https://cloud.githubusercontent.com/assets/10737439/6951421/e676ad54-d8c3-11e4-904f-fd061dac41c9.png)
TFOB disabled:
![2015-04-01 23 05 39](https://cloud.githubusercontent.com/assets/10737439/6951428/ee83a6e6-d8c3-11e4-9829-ff6b018930bc.png)
Actually, the toolbar color gradient is also different.

**Comment by Quicksaver** [comment]
That's weird, that seems like a previous bug I thought I had seen and fixed already. Thanks for letting me know, I'll be sure to check it out.

**Comment by DotTheI** [comment]
Thank you! 
And I appreciate very much that you have developed this space saving add-on!

**Comment by Quicksaver** [comment]
I'm glad you like it. :)

**Comment by DotTheI** [comment]
Strangely enough, the issue does not persist in full screen mode

**Comment by Quicksaver** [comment]
The border looks fine for me. What OSX; fierfox and add-on versions are you running? And does it also appear like that if you disable all your other add-ons and themes except for TFOB?

**Comment by DotTheI** [comment]
I am running OS X 10.10.3 and Firefox 37.0.2. I have tried disabling all the other add-ons, but it didn't help

**Comment by Quicksaver** [comment]
I have a feeling this happens only on OS X 10, and that beta version 1.1.12b3 will work correctly. Could you give it a go please (at the top of https://addons.mozilla.org/firefox/addon/the-fox-only-better/versions/) and let me know?

**Comment by DotTheI** [comment]
Installing beta 3 fixed the issue! Thank you!!

**Comment by Quicksaver** [comment]
Great! No problem.
