### ISSUE TITLE
The minibar does not disappear

### ISSUE THREAD

**Issue by 70599** [Quicksaver/The-Fox--Only-Better#98]
screen shot:
http://i.share.pho.to/a084d5cf_o.png

is there anyway to hide the minibar completely(by css or something other)?

**Comment by Quicksaver** [comment]
The mini bar should disappear after a few seconds. Does this happen every time, or can you give me specific steps to reproduce this? Also, please try disabling all your other add-ons and see if the mini bar still stays stuck like that.

**Comment by 70599** [comment]
Mini bar does not disappear forever when the issue happens.
No idea how to make this issue happen, it seems just randomly.

>"please try disabling all your other add-ons and see if the mini bar still stays stuck like that."
I will try this when it happens next time, thanks.

BTW: is there anyway to hide the minibar completely(by stylish css or something other)?

**Comment by Quicksaver** [comment]
> I will try this when it happens next time, thanks.

You would have to disable them before (especially since many add-ons require a restart for this), and see if the mini bar "gets" stuck, as it's unlikely to unstuck itself after it does get stuck.

> is there anyway to hide the minibar completely(by stylish css or something other)?

You can just disable it in the preferences. Or use the keyboard shortcut to disable-reenable Slim Chrome when it does get stuck; this should be enough to get it "unstuck". But I would really like to try and fix the problem itself if I can, so it doesn't get stuck at all for you.

**Comment by 70599** [comment]
Finally, I found how to make this issue happen.

1. Open https://cloud.digitalocean.com/login
2. Focus on password input filed(minibar shows up at this momment)
3. Select other browser-tab
4. The minibar does not disappear

Tested using TFOB 1.1.12b1 on Firefox 40.0a1.
extensions.thefoxonlybetter.miniOnAllInput, 
extensions.thefoxonlybetter.miniOnChangeLocation,
extensions.thefoxonlybetter.miniOnTabSelect,
ALL seted to false.

PS:
Seems the password input filed may cause this issue.
Unfocuseing the password input filed may get it unstucked.

**Comment by Quicksaver** [comment]
You're right of course, it was an error in the logic I wrote, very simple to fix. Could you try out beta version 2b2 (at the top of https://addons.mozilla.org/firefox/addon/the-fox-only-better/versions/) and see if that also fixes the issue for you?

**Comment by 70599** [comment]
Seems fixed with 1.1.12b2.
Thanks.
