### ISSUE TITLE
all panels usually become unobtainable right after startup

### ISSUE THREAD

**Issue by TAImatem** [Quicksaver/The-Fox--Only-Better#99]
sometimes right after startup of FF all panels (except for one with tabs) can become totally unaccessible, even if I disable "slim chrome", nothing pops up. So, I always need to keep in mind to disable "slim chrome" before closing the FF. Maybe it's just incompatibility or something wrong  with my browser...

**Comment by Quicksaver** [comment]
What do you mean with "panels are inaccessible"? What panels? Exactly for you what doesn't work after a restart of firefox?

**Comment by TAImatem** [comment]
Nevermind, I don't know why, but now it's not happens anymore.
